// The gauntlet map: the country, and the grounds you have to get through.
//
// The outline is drawn as one continuous shape — a single silhouette, no
// internal lines of any kind. Stations sit on real city positions, each drawn
// as a small isometric stadium (an SVG bowl, no external assets).

const GM_VIEW = { w: 300, h: 760 };

// Real border geometry, not a freehand guess: generated by
// scripts/build_map_path.js from public country outlines and projected into the
// viewBox. Drawn as one path so the country reads as a SINGLE silhouette — no
// internal lines anywhere.
const ISRAEL_PATH = `M 260.7 124.2 L 231.9 185.3 L 172 158.4 L 137.4 287.5 L 179 309.3 L 136.7 335.9 L 129.6 387 L 207.4 360.7 L 211.2 436.1 L 128.8 746 L 20 413 L 68.2 349.1 L 56.9 338.1 L 100.6 247.5 L 134.2 101.2 L 157.9 52.2 L 162.4 50.2 L 217.8 50.5 L 233.1 16.5 L 277.5 14 L 280 93.3 L 257.5 122.8 L 260.7 124.2 Z M 231.9 185.3 L 231.8 303.8 L 207.4 360.7 L 129.6 387 L 136.7 335.9 L 179 309.3 L 137.4 287.5 L 172 158.4 L 231.9 185.3 Z`;

// The same projection the generator printed, so a city's real coordinates land
// exactly where they belong on the outline.
const GM_PROJ = { offX: 20.02, lon0: 34.265433, kx: 0.8536, scale: 193.85, offY: 14.00, lat1: 33.277426 };
const gmX = lon => GM_PROJ.offX + (lon - GM_PROJ.lon0) * GM_PROJ.kx * GM_PROJ.scale;
const gmY = lat => GM_PROJ.offY + (GM_PROJ.lat1 - lat) * GM_PROJ.scale;

// station → where it sits on the map (viewBox coords) and which club-seasons
// it can draw from. Real grounds, so the map reads like the country.
const GM_CITIES = [
  { id: 'ironi-ks',           name: 'קריית שמונה', lat: 33.207, lon: 35.569 },
  { id: 'ironi-tiberias',     name: 'טבריה',        lat: 32.795, lon: 35.530 },
  { id: 'bnei-sakhnin',       name: 'סכנין',        lat: 32.865, lon: 35.298 },
  { id: 'maccabi-ahi-naz',    name: 'נצרת',         lat: 32.700, lon: 35.303 },
  { id: 'maccabi-bnei-raina', name: 'ריינה',        lat: 32.727, lon: 35.312 },
  { id: 'hapoel-galil',       name: 'נוף הגליל',    lat: 32.706, lon: 35.317 },
  { id: 'hapoel-aco',         name: 'עכו',          lat: 32.928, lon: 35.082 },
  { id: 'maccabi-haifa',      name: 'חיפה',         lat: 32.794, lon: 34.990 },
  { id: 'hapoel-haifa',       name: 'חיפה',         lat: 32.780, lon: 35.020 },
  { id: 'hapoel-hadera',      name: 'חדרה',         lat: 32.434, lon: 34.919 },
  { id: 'maccabi-netanya',    name: 'נתניה',        lat: 32.328, lon: 34.856 },
  { id: 'hapoel-kfar-saba',   name: 'כפר סבא',      lat: 32.175, lon: 34.907 },
  { id: 'hapoel-raanana',     name: 'רעננה',        lat: 32.184, lon: 34.871 },
  { id: 'hapoel-rhs',         name: 'רמת השרון',    lat: 32.146, lon: 34.839 },
  { id: 'maccabi-herzliya',   name: 'הרצליה',       lat: 32.166, lon: 34.843 },
  { id: 'maccabi-pt',         name: 'פתח תקווה',    lat: 32.087, lon: 34.887 },
  { id: 'hapoel-pt',          name: 'פתח תקווה',    lat: 32.100, lon: 34.900 },
  { id: 'hapoel-rg',          name: 'רמת גן',       lat: 32.070, lon: 34.824 },
  { id: 'hakoah-rg',          name: 'רמת גן',       lat: 32.078, lon: 34.836 },
  { id: 'maccabi-tlv',        name: 'תל אביב',      lat: 32.105, lon: 34.793 },
  { id: 'hapoel-tlv',         name: 'תל אביב',      lat: 32.062, lon: 34.796 },
  { id: 'bnei-yehuda',        name: 'תל אביב',      lat: 32.042, lon: 34.786 },
  { id: 'hapoel-holon',       name: 'חולון',        lat: 32.015, lon: 34.779 },
  { id: 'hapoel-rishonim',    name: 'ראשל"צ',       lat: 31.971, lon: 34.789 },
  { id: 'sakhnina-ns',        name: 'נס ציונה',     lat: 31.929, lon: 34.799 },
  { id: 'ms-ashdod',          name: 'אשדוד',        lat: 31.802, lon: 34.656 },
  { id: 'beitar-jerusalem',   name: 'ירושלים',      lat: 31.768, lon: 35.214 },
  { id: 'hapoel-jerusalem',   name: 'ירושלים',      lat: 31.790, lon: 35.200 },
  { id: 'hapoel-ashkelon',    name: 'אשקלון',       lat: 31.669, lon: 34.574 },
  { id: 'maccabi-kg',         name: 'קריית גת',     lat: 31.610, lon: 34.764 },
  { id: 'hapoel-beersheba',   name: 'באר שבע',      lat: 31.252, lon: 34.791 },
];

function gmCityFor(teamId) {
  const c = GM_CITIES.find(x => x.id === teamId);
  return c ? { ...c, x: gmX(c.lon), y: gmY(c.lat) } : null;
}

// A small isometric ground: an ellipse for the bowl, a lighter pitch inside,
// and a shadow so it sits on the map instead of floating over it.
function gmStadiumSVG(x, y, { size = 1, state = 'locked', elite = false } = {}) {
  const w = 26 * size, h = 13 * size;
  const stand = elite ? '#8b5cf6' : state === 'done' ? '#3f6f4a' : state === 'next' ? '#d4af37' : '#4b5563';
  const pitch = state === 'done' ? '#2b4a33' : '#2f7d4a';
  const glow  = state === 'next' ? `<ellipse cx="${x}" cy="${y + h * 0.35}" rx="${w * 0.95}" ry="${h * 0.95}" fill="#d4af37" opacity=".22"/>` : '';
  return `
    <g class="gm-stadium gm-${state}${elite ? ' gm-elite' : ''}">
      ${glow}
      <ellipse cx="${x}" cy="${y + h * 0.55}" rx="${w * 0.72}" ry="${h * 0.42}" fill="#000" opacity=".35"/>
      <ellipse cx="${x}" cy="${y}" rx="${w * 0.72}" ry="${h * 0.72}" fill="${stand}"/>
      <ellipse cx="${x}" cy="${y - h * 0.12}" rx="${w * 0.72}" ry="${h * 0.72}" fill="${stand}" opacity=".85"/>
      <ellipse cx="${x}" cy="${y - h * 0.12}" rx="${w * 0.46}" ry="${h * 0.44}" fill="${pitch}"/>
      <line x1="${x - w * 0.46}" y1="${y - h * 0.12}" x2="${x + w * 0.46}" y2="${y - h * 0.12}" stroke="#ffffff55" stroke-width=".6"/>
      <circle cx="${x}" cy="${y - h * 0.12}" r="${h * 0.14}" fill="none" stroke="#ffffff55" stroke-width=".6"/>
    </g>`;
}

// Renders the whole map. `stations` = [{station, teamId, season, ovr, elite}],
// `at` = the index you are standing on.
function renderGauntletMap(container, stations, at = 0) {
  if (!container) return;

  // Half the league lives in Gush Dan, so grounds land on top of each other.
  // Place them one by one and push each new one away from whatever is already
  // there — the pin moves, the country doesn't.
  const placed = [];
  const spots = stations.map((st, i) => {
    const city = gmCityFor(st.teamId) || { x: 150, y: 120 + i * 70 };
    let { x, y } = city;
    const MIN = 34;
    for (let guard = 0; guard < 60; guard++) {
      const hit = placed.find(p => Math.hypot(p.x - x, p.y - y) < MIN);
      if (!hit) break;
      const ang = Math.atan2(y - hit.y || 0.01, x - hit.x || 0.01);
      x = hit.x + Math.cos(ang) * MIN;
      y = hit.y + Math.sin(ang) * MIN;
    }
    placed.push({ x, y });
    return { x, y, home: city };
  });

  const marks = stations.map((st, i) => {
    const city = spots[i];
    const state = i < at ? 'done' : i === at ? 'next' : 'locked';
    // Only the number rides on the map. Names and ratings live in the list
    // below: four Gush Dan clubs in one run made overlapping labels unreadable.
    return `
      <g class="gm-station" data-station="${i}">
        ${gmStadiumSVG(city.x, city.y, { size: i === at ? 1.3 : 1, state, elite: !!st.elite })}
        <text class="gm-num" x="${city.x}" y="${city.y + 2}" text-anchor="middle">${i + 1}</text>
      </g>`;
  }).join('');

  // the road between grounds, drawn behind them
  const road = spots.map(s => `${s.x.toFixed(1)},${s.y.toFixed(1)}`).join(' ');

  container.innerHTML = `
    <svg class="gm-svg" viewBox="0 0 ${GM_VIEW.w} ${GM_VIEW.h}" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="gm-land" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stop-color="#1c3d2a"/>
          <stop offset="55%" stop-color="#17311f"/>
          <stop offset="100%" stop-color="#2a2a1c"/>
        </linearGradient>
        <!-- The border is drawn by dilating the FILLED silhouette, not by
             stroking the path: a stroke would trace every sub-polygon and put
             internal lines across the country. This traces only the outer edge. -->
        <filter id="gm-edge" x="-10%" y="-6%" width="120%" height="112%">
          <feMorphology in="SourceAlpha" operator="dilate" radius="1.2" result="fat"/>
          <feFlood flood-color="#4ea36a"/>
          <feComposite in2="fat" operator="in" result="edge"/>
          <feMerge><feMergeNode in="edge"/><feMergeNode in="SourceGraphic"/></feMerge>
        </filter>
      </defs>
      <path class="gm-land" d="${ISRAEL_PATH}" fill="url(#gm-land)" fill-rule="nonzero" filter="url(#gm-edge)"/>
      <polyline class="gm-road" points="${road}" fill="none" stroke="#d4af3766" stroke-width="1.6" stroke-dasharray="4 4"/>
      ${marks}
    </svg>
    <ol class="gm-list">${stations.map((st, i) => {
      const club = (typeof TEAMS === 'object' && TEAMS[st.teamId] ? TEAMS[st.teamId].name : st.teamId);
      const cls = i < at ? 'done' : i === at ? 'next' : '';
      return `<li class="gm-li ${cls}${st.elite ? ' elite' : ''}">
        <span class="gm-li-n">${i + 1}</span>
        <span class="gm-li-club">${club} · ${st.season}</span>
        ${st.elite ? '<span class="gm-li-elite">ELITE</span>' : ''}
        <span class="gm-li-ovr">${st.ovr}</span>
      </li>`;
    }).join('')}</ol>`;
}

/* ── station picking ──────────────────────────────────────────────────────── */
// Every club-season we hold, rated by its top-11 average — the same measure the
// game already uses for opponents. That list IS the difficulty ladder.
let _gmLadder = null;
function gmLadder() {
  if (_gmLadder) return _gmLadder;
  const rate = sq => {
    const top = [...sq.players].sort((a, b) => b.ovr - a.ovr).slice(0, 11);
    return Math.round(top.reduce((s, p) => s + p.ovr, 0) / top.length);
  };
  return (_gmLadder = SQUADS
    .filter(sq => gmCityFor(sq.teamId))          // only clubs we can place on the map
    .map(sq => ({ teamId: sq.teamId, season: sq.season, ovr: rate(sq) }))
    .sort((a, b) => a.ovr - b.ovr));
}

// Eight stations of rising difficulty. The last two are drawn from the very top
// (the bosses); the rest are spread across bands so a run climbs steadily.
// One mid-run station is marked ELITE — harder, richer spoils, always skippable.
function gmPickStations(rng = Math.random) {
  const ladder = gmLadder();                   // already sorted weakest → strongest
  const n = ladder.length;
  // Slice by POSITION in the ladder, not by hardcoded rating bands: fixed bands
  // left the top ones nearly empty, the pick fell back to the whole list, and a
  // run could end on a station weaker than the one before it.
  const used = new Set();
  const out = [];
  for (let i = 0; i < 8; i++) {
    const lo = Math.floor((i / 8) * n);
    const hi = i === 7 ? n : Math.floor(((i + 1) / 8) * n);
    const slice = ladder.slice(i === 7 ? Math.floor(n * 0.94) : lo, hi);   // boss = top 6%
    let s, guard = 0;
    do { s = slice[Math.floor(rng() * slice.length)]; guard++; }
    while (s && used.has(s.teamId + s.season) && guard < 40);
    if (!s) continue;
    used.add(s.teamId + s.season);
    out.push({ ...s, station: i, elite: false });
  }
  const eliteIdx = 3 + Math.floor(rng() * 3);          // somewhere in the middle
  if (out[eliteIdx]) { out[eliteIdx].elite = true; out[eliteIdx].ovr += 4; }
  return out;
}

/* ── screen ───────────────────────────────────────────────────────────────── */
function showGauntlet() {
  showScreen('gauntlet');
  const back = document.getElementById('gauntlet-back');
  if (back) back.onclick = () => showScreen('welcome');
  const reroll = document.getElementById('gauntlet-reroll');
  const draw = () => renderGauntletMap(document.getElementById('gauntlet-map'), gmPickStations(), 0);
  if (reroll) reroll.onclick = draw;
  draw();
}
