// The gauntlet map: the country, and the grounds you have to get through.
//
// The outline is drawn as one continuous shape — a single silhouette, no
// internal lines of any kind. Stations sit on real city positions, each drawn
// as a small isometric stadium (an SVG bowl, no external assets).

const GM_VIEW = { w: 300, h: 760 };

// Real border geometry, not a freehand guess: generated by
// scripts/build_map_path.js from public country outlines and projected into the
// viewBox. Drawn as one path so the country reads as a SINGLE silhouette — no
// internal lines anywhere.
const ISRAEL_PATH = `M 260.7 124.2 L 231.9 185.3 L 172 158.4 L 137.4 287.5 L 179 309.3 L 136.7 335.9 L 129.6 387 L 207.4 360.7 L 211.2 436.1 L 128.8 746 L 20 413 L 68.2 349.1 L 56.9 338.1 L 100.6 247.5 L 134.2 101.2 L 157.9 52.2 L 162.4 50.2 L 217.8 50.5 L 233.1 16.5 L 277.5 14 L 280 93.3 L 257.5 122.8 L 260.7 124.2 Z M 231.9 185.3 L 231.8 303.8 L 207.4 360.7 L 129.6 387 L 136.7 335.9 L 179 309.3 L 137.4 287.5 L 172 158.4 L 231.9 185.3 Z`;

// The same projection the generator printed, so a city's real coordinates land
// exactly where they belong on the outline.
const GM_PROJ = { offX: 20.02, lon0: 34.265433, kx: 0.8536, scale: 193.85, offY: 14.00, lat1: 33.277426 };
const gmX = lon => GM_PROJ.offX + (lon - GM_PROJ.lon0) * GM_PROJ.kx * GM_PROJ.scale;
const gmY = lat => GM_PROJ.offY + (GM_PROJ.lat1 - lat) * GM_PROJ.scale;

// station → where it sits on the map (viewBox coords) and which club-seasons
// it can draw from. Real grounds, so the map reads like the country.
const GM_CITIES = [
  { id: 'ironi-ks',           name: 'קריית שמונה', lat: 33.207, lon: 35.569 },
  { id: 'ironi-tiberias',     name: 'טבריה',        lat: 32.795, lon: 35.530 },
  { id: 'bnei-sakhnin',       name: 'סכנין',        lat: 32.865, lon: 35.298 },
  { id: 'maccabi-ahi-naz',    name: 'נצרת',         lat: 32.700, lon: 35.303 },
  { id: 'maccabi-bnei-raina', name: 'ריינה',        lat: 32.727, lon: 35.312 },
  { id: 'hapoel-galil',       name: 'נוף הגליל',    lat: 32.706, lon: 35.317 },
  { id: 'hapoel-aco',         name: 'עכו',          lat: 32.928, lon: 35.082 },
  { id: 'maccabi-haifa',      name: 'חיפה',         lat: 32.794, lon: 34.990 },
  { id: 'hapoel-haifa',       name: 'חיפה',         lat: 32.780, lon: 35.020 },
  { id: 'hapoel-hadera',      name: 'חדרה',         lat: 32.434, lon: 34.919 },
  { id: 'maccabi-netanya',    name: 'נתניה',        lat: 32.328, lon: 34.856 },
  { id: 'hapoel-kfar-saba',   name: 'כפר סבא',      lat: 32.175, lon: 34.907 },
  { id: 'hapoel-raanana',     name: 'רעננה',        lat: 32.184, lon: 34.871 },
  { id: 'hapoel-rhs',         name: 'רמת השרון',    lat: 32.146, lon: 34.839 },
  { id: 'maccabi-herzliya',   name: 'הרצליה',       lat: 32.166, lon: 34.843 },
  { id: 'maccabi-pt',         name: 'פתח תקווה',    lat: 32.087, lon: 34.887 },
  { id: 'hapoel-pt',          name: 'פתח תקווה',    lat: 32.100, lon: 34.900 },
  { id: 'hapoel-rg',          name: 'רמת גן',       lat: 32.070, lon: 34.824 },
  { id: 'hakoah-rg',          name: 'רמת גן',       lat: 32.078, lon: 34.836 },
  { id: 'maccabi-tlv',        name: 'תל אביב',      lat: 32.105, lon: 34.793 },
  { id: 'hapoel-tlv',         name: 'תל אביב',      lat: 32.062, lon: 34.796 },
  { id: 'bnei-yehuda',        name: 'תל אביב',      lat: 32.042, lon: 34.786 },
  { id: 'hapoel-holon',       name: 'חולון',        lat: 32.015, lon: 34.779 },
  { id: 'hapoel-rishonim',    name: 'ראשל"צ',       lat: 31.971, lon: 34.789 },
  { id: 'sakhnina-ns',        name: 'נס ציונה',     lat: 31.929, lon: 34.799 },
  { id: 'ms-ashdod',          name: 'אשדוד',        lat: 31.802, lon: 34.656 },
  { id: 'beitar-jerusalem',   name: 'ירושלים',      lat: 31.768, lon: 35.214 },
  { id: 'hapoel-jerusalem',   name: 'ירושלים',      lat: 31.790, lon: 35.200 },
  { id: 'hapoel-ashkelon',    name: 'אשקלון',       lat: 31.669, lon: 34.574 },
  { id: 'maccabi-kg',         name: 'קריית גת',     lat: 31.610, lon: 34.764 },
  { id: 'hapoel-beersheba',   name: 'באר שבע',      lat: 31.252, lon: 34.791 },
];

function gmCityFor(teamId) {
  const c = GM_CITIES.find(x => x.id === teamId);
  return c ? { ...c, x: gmX(c.lon), y: gmY(c.lat) } : null;
}

// A club marker in the club's real colours. If you ever decide to add actual
// crests, drop <teamId>.png into /crests/ and it is used automatically — the
// colours stay as the fallback, so nothing breaks when a file is missing.
// (Real crests are trademarks; that call is the owner's, not the code's.)
function gmCrestSVG(x, y, teamId, { size = 1, state = 'locked', elite = false } = {}) {
  const t = (typeof TEAMS === 'object' && TEAMS[teamId]) || { primaryColor: '#4b5563', secondaryColor: '#fff' };
  const r = 11 * size;
  const dim = state === 'locked' ? '.55' : '1';
  const ring = elite ? '#8b5cf6' : state === 'next' ? '#d4af37' : state === 'done' ? '#3f6f4a' : '#20262e';
  const glow = state === 'next' ? `<circle cx="${x}" cy="${y}" r="${r * 1.9}" fill="#d4af37" opacity=".20"/>` : '';
  return `
    <g class="gm-stadium gm-${state}${elite ? ' gm-elite' : ''}" opacity="${dim}">
      ${glow}
      <circle cx="${x}" cy="${y}" r="${r + 3.5}" fill="#0b0f14" opacity=".92"/>
      <circle cx="${x}" cy="${y}" r="${r + 2}" fill="none" stroke="${ring}" stroke-width="2"/>
      <circle cx="${x}" cy="${y}" r="${r}" fill="#f2f4f7" opacity=".96"/>
      <path d="M ${x - r * 0.8} ${y - r * 0.7} h ${r * 1.6} v ${r * 0.5}
               a ${r * 0.8} ${r * 0.8} 0 0 1 -${r * 0.8} ${r * 0.95}
               a ${r * 0.8} ${r * 0.8} 0 0 1 -${r * 0.8} -${r * 0.95} Z" fill="${t.primaryColor}"/>
      <image class="gm-crest-img" href="crests/${teamId}.png" x="${x - r * 0.92}" y="${y - r * 0.92}"
             width="${r * 1.84}" height="${r * 1.84}" preserveAspectRatio="xMidYMid meet"
             onerror="this.remove()"/>
    </g>`;
}

// A small isometric ground: an ellipse for the bowl, a lighter pitch inside,
// and a shadow so it sits on the map instead of floating over it.
function gmStadiumSVG(x, y, { size = 1, state = 'locked', elite = false } = {}) {
  const w = 26 * size, h = 13 * size;
  const stand = elite ? '#8b5cf6' : state === 'done' ? '#3f6f4a' : state === 'next' ? '#d4af37' : '#4b5563';
  const pitch = state === 'done' ? '#2b4a33' : '#2f7d4a';
  const glow  = state === 'next' ? `<ellipse cx="${x}" cy="${y + h * 0.35}" rx="${w * 0.95}" ry="${h * 0.95}" fill="#d4af37" opacity=".22"/>` : '';
  return `
    <g class="gm-stadium gm-${state}${elite ? ' gm-elite' : ''}">
      ${glow}
      <ellipse cx="${x}" cy="${y + h * 0.55}" rx="${w * 0.72}" ry="${h * 0.42}" fill="#000" opacity=".35"/>
      <ellipse cx="${x}" cy="${y}" rx="${w * 0.72}" ry="${h * 0.72}" fill="${stand}"/>
      <ellipse cx="${x}" cy="${y - h * 0.12}" rx="${w * 0.72}" ry="${h * 0.72}" fill="${stand}" opacity=".85"/>
      <ellipse cx="${x}" cy="${y - h * 0.12}" rx="${w * 0.46}" ry="${h * 0.44}" fill="${pitch}"/>
      <line x1="${x - w * 0.46}" y1="${y - h * 0.12}" x2="${x + w * 0.46}" y2="${y - h * 0.12}" stroke="#ffffff55" stroke-width=".6"/>
      <circle cx="${x}" cy="${y - h * 0.12}" r="${h * 0.14}" fill="none" stroke="#ffffff55" stroke-width=".6"/>
    </g>`;
}

// Renders the map. `at` is the index of the row you are standing on; rows below
// it are done, the row itself is choosable, everything above is locked.
function renderGauntletMap(container, at = 0, over = false) {
  if (!container) return;
  const layout = gmLayout();
  const short = id => (typeof clubShortName === 'function'
    ? clubShortName((TEAMS[id] || {}).name || id)
    : (TEAMS[id] || {}).name || id);

  // roads first, so they sit behind the grounds
  const roads = [];
  for (let i = 0; i < layout.length - 1; i++) {
    for (const from of layout[i]) {
      for (const to of layout[i + 1]) {
        const done = i < at;
        roads.push(`<line x1="${from.x.toFixed(1)}" y1="${from.y.toFixed(1)}"
          x2="${to.x.toFixed(1)}" y2="${to.y.toFixed(1)}"
          stroke="${done ? '#3f6f4a' : '#d4af3744'}" stroke-width="1.4" stroke-dasharray="4 4"/>`);
      }
    }
  }

  const nodes = GM_RUN.map((row, ri) => {
    // a finished run leaves nothing choosable — the cleared rows still read as
    // cleared, but no ground invites a click that gtChoose would refuse
    const state = ri < at ? 'done' : (ri === at && !over) ? 'next' : 'locked';
    return layout[ri].map((pt, ni) => {
      if (row.kind === 'shop') {
        return `
          <g class="gm-station gm-shop-node ${state}">
            <circle cx="${pt.x}" cy="${pt.y}" r="13" fill="#0b0f14" opacity=".92"/>
            <circle cx="${pt.x}" cy="${pt.y}" r="11.5" fill="none" stroke="${state === 'locked' ? '#20262e' : '#8b5cf6'}" stroke-width="2"/>
            <text class="gm-shop-icon" x="${pt.x}" y="${pt.y + 4}" text-anchor="middle">🛒</text>
          </g>`;
      }
      const n = row.nodes[ni];
      const elite = typeof gtIsElite === 'function' && gtIsElite(n);
      const size = row.boss ? 1.35 : 1;
      // Name only, and staggered: three grounds on one line put their captions
      // on top of each other. The season and rating are in the list below.
      const dy = layout[ri].length > 2 ? (ni === 1 ? 30 : 22) : 22;
      const label = state === 'next'
        ? `<text class="gm-label" x="${pt.x}" y="${pt.y + dy * size}" text-anchor="middle">${short(n.teamId)}</text>`
        : '';
      return `
        <g class="gm-station ${state}${elite ? ' elite' : ''}" data-row="${ri}" data-node="${ni}">
          ${gmCrestSVG(pt.x, pt.y, n.teamId, { size, state, elite })}
          <g class="gm-ovr-badge">
            <rect x="${pt.x + 4 * size}" y="${pt.y + 4 * size}" width="${17 * size}" height="${11 * size}" rx="${5 * size}"
                  fill="#0b0f14" stroke="${elite ? '#8b5cf6' : '#d4af37'}" stroke-width="1"/>
            <text class="gm-ovr" x="${pt.x + 12.5 * size}" y="${pt.y + 12.5 * size}" text-anchor="middle">${typeof gtShownOvr === 'function' ? gtShownOvr(n) : n.ovr}</text>
          </g>
          ${row.boss ? `<text class="gm-boss" x="${pt.x}" y="${pt.y - 20 * size}" text-anchor="middle">${ri === GM_RUN.length - 1 ? 'הבוס הסופי' : 'בוס'}</text>` : ''}
          ${elite ? `<text class="gm-elite-tag" x="${pt.x}" y="${pt.y - 17}" text-anchor="middle">ELITE</text>` : ''}
          ${label}
        </g>`;
    }).join('');
  }).join('');

  // On a shop stop the panel comes first: the map is context, the shop is the
  // reason you are standing here, and it must not sit below a full-height map.
  const picker = gmRoadPicker(at, over);
  // a shop stop or a finished run gets the panel above the map: the map is
  // context, the panel is the reason you are standing here
  const shopFirst = !GM_RUN[at] || GM_RUN[at].kind === 'shop';

  container.innerHTML = `
    ${typeof gtRelicBarHTML === 'function' ? gtRelicBarHTML() : ''}
    ${shopFirst ? picker : ''}
    <svg class="gm-svg" viewBox="0 0 ${GM_VIEW.w} ${GM_VIEW.h}" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="gm-land" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stop-color="#0e1f18"/>
          <stop offset="55%" stop-color="#0b1a14"/>
          <stop offset="100%" stop-color="#12160f"/>
        </linearGradient>
        <radialGradient id="gm-glow">
          <stop offset="0%" stop-color="#ffcf6b" stop-opacity=".38"/>
          <stop offset="60%" stop-color="#ffb347" stop-opacity=".10"/>
          <stop offset="100%" stop-color="#ffb347" stop-opacity="0"/>
        </radialGradient>
        <!-- The border is drawn by dilating the FILLED silhouette, not by
             stroking the path: a stroke would trace every sub-polygon and put
             internal lines across the country. This traces only the outer edge. -->
        <filter id="gm-edge" x="-10%" y="-6%" width="120%" height="112%">
          <feMorphology in="SourceAlpha" operator="dilate" radius="1.2" result="fat"/>
          <feFlood flood-color="#4ea36a"/>
          <feComposite in2="fat" operator="in" result="edge"/>
          <feMerge><feMergeNode in="edge"/><feMergeNode in="SourceGraphic"/></feMerge>
        </filter>
      </defs>
      <path class="gm-land" d="${ISRAEL_PATH}" fill="url(#gm-land)" fill-rule="nonzero" filter="url(#gm-edge)"/>
      <g class="gm-lights">${gmLightsSVG()}</g>
      <g class="gm-roads">${roads.join('')}</g>
      ${nodes}
    </svg>
    ${shopFirst ? '' : picker}`;
}

// "Pick your road": the row you are standing on, as tappable cards under the
// map — a 17-node map is hard to aim at on a phone, and the description only
// fits down here anyway.
function gmRoadPicker(at, over) {
  const row = GM_RUN[at];
  if (over) {
    const run = typeof gtRun === 'function' ? gtRun() : { log: [] };
    const cleared = (run.log || []).filter(l => l.outcome === 'W').length;
    const best = typeof gtBest === 'function' ? gtBest() : { depth: 0 };
    const last = (run.log || [])[run.log.length - 1];
    const club = last ? ((TEAMS[last.teamId] || {}).name || '') + ' ' + last.season : '';
    return `
      <div class="gm-picker gt-over">
        <div class="gm-picker-head">💀 הריצה נגמרה</div>
        <p class="gm-picker-sub">${cleared} ניצחונות${club ? ` · נעצרת מול ${club}` : ''} · השיא שלך: ${best.depth}</p>
        <button class="btn-primary btn-full" id="gt-new-run">🔁 ריצה חדשה</button>
      </div>`;
  }
  if (!row) {
    return typeof gtVictoryHTML === 'function'
      ? gtVictoryHTML() : `<p class="gm-picker-head">🏆 עברת את כל המסלול</p>`;
  }
  if (row.kind === 'shop') return typeof gtShopHTML === 'function' ? gtShopHTML() : '';

  const title = row.boss
    ? (at === GM_RUN.length - 1 ? '⚔️ הבוס הסופי' : '⚔️ בוס')
    : row.nodes.length > 1 ? 'בחר את הדרך' : 'המשחק הבא';
  const sub = row.nodes.length > 1
    ? 'אפשר ללחוץ על כרטיס למטה או על המגרש במפה. יריבה קשה יותר - שלל טוב יותר.'
    : 'אין מסלול עוקף.';
  return `
    <div class="gm-picker">
      <div class="gm-picker-round">קרב ${row.round} מתוך 8</div>
      <div class="gm-picker-head">${title}</div>
      <p class="gm-picker-sub">${sub}</p>
      ${row.nodes.map((n, ni) => {
        const club = (TEAMS[n.teamId] || {}).name || n.teamId;
        const elite = typeof gtIsElite === 'function' && gtIsElite(n);
        const desc = (typeof siteText === 'function'
          ? siteText('gt-desc-' + n.teamId + '-' + n.season.replace('/', '-'), n.desc) : n.desc) || '';
        // a scout earns his keep here: the four lines behind the headline number
        const scout = (typeof gtScouting === 'function' && gtScouting() && typeof gtOpponent === 'function')
          ? (o => `<span class="gm-road-scout" dir="ltr">GK ${Math.round(o.gk)} · DEF ${Math.round(o.def)} · MID ${Math.round(o.mid)} · ATK ${Math.round(o.atk)}</span>`)(gtOpponent(n))
          : '';
        return `
        <button class="gm-road ${elite ? 'elite' : ''}" data-row="${at}" data-node="${ni}">
          <img class="gm-road-crest" src="crests/${n.teamId}.png" alt="" onerror="this.style.visibility='hidden'">
          <span class="gm-road-main">
            <span class="gm-road-club">${club} <span class="gm-road-season">${n.season}</span></span>
            <span class="gm-road-desc">${desc}</span>
            ${scout}
          </span>
          ${elite ? '<span class="gm-road-elite">ELITE</span>' : ''}
          <span class="gm-road-ovr">${typeof gtShownOvr === 'function' ? gtShownOvr(n) : n.ovr}</span>
        </button>`;
      }).join('')}
    </div>`;
}

/* ── geometry: what counts as "inside the country" ────────────────────────── */
// The path is already numeric viewBox coordinates, so it can be parsed straight
// into polygons and used for hit-testing — that is how the lights know where to
// fall and how a crest is kept from drifting into the sea.
const GM_POLYS = (() => {
  return ISRAEL_PATH.trim().split('M ').filter(Boolean).map(chunk =>
    chunk.replace('Z', '').trim().split(' L ').map(pair => pair.trim().split(/\s+/).map(Number))
  );
})();
function gmInside(x, y) {
  let inside = false;
  for (const poly of GM_POLYS) {
    for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
      const [xi, yi] = poly[i], [xj, yj] = poly[j];
      if ((yi > y) !== (yj > y) && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
    }
  }
  return inside;
}
const GM_CENTER = (() => {
  const pts = GM_POLYS.flat();
  return [pts.reduce((s, p) => s + p[0], 0) / pts.length, pts.reduce((s, p) => s + p[1], 0) / pts.length];
})();
// pulls a point back onto land, with room to spare for the marker itself
function gmClampInside(x, y, margin = 12) {
  const ok = (px, py) => gmInside(px, py) &&
    gmInside(px + margin, py) && gmInside(px - margin, py) &&
    gmInside(px, py + margin) && gmInside(px, py - margin);
  if (ok(x, y)) return { x, y };
  for (let t = 0.06; t <= 1; t += 0.06) {
    const nx = x + (GM_CENTER[0] - x) * t, ny = y + (GM_CENTER[1] - y) * t;
    if (ok(nx, ny)) return { x: nx, y: ny };
  }
  return { x: GM_CENTER[0], y: GM_CENTER[1] };
}

// Night lights. Not a handful of dots — a field of them, scattered inside the
// country and weighted towards where people actually live, so the coastal strip
// and Jerusalem burn bright and the Negev fades to almost nothing.
const GM_HUBS = [   // [lat, lon, pull] — pull is roughly how big the place is
  [32.085, 34.781, 30], [32.070, 34.824, 22], [32.015, 34.779, 16], [31.971, 34.789, 16],
  [32.166, 34.843, 12], [32.087, 34.887, 18], [32.175, 34.907, 12], [31.929, 34.799, 10],
  [31.802, 34.656, 15], [31.669, 34.574, 12], [31.610, 34.764,  8], [32.328, 34.856, 14],
  [32.434, 34.919, 10], [32.794, 34.990, 24], [32.928, 35.082, 10], [32.865, 35.298,  8],
  [32.700, 35.303, 12], [32.795, 35.530,  8], [33.207, 35.569,  6], [31.768, 35.214, 28],
  [31.890, 35.010, 10], [31.252, 34.791, 18], [30.610, 34.800,  5], [29.557, 34.952,  6],
  [31.418, 34.598,  8], [32.640, 35.290,  8], [31.500, 34.900,  6], [32.500, 35.470,  6],
];
// a tiny deterministic PRNG — the sky must look the same on every render
function gmRand(seed) {
  let t = seed >>> 0;
  return () => { t += 0x6D2B79F5; let r = Math.imul(t ^ (t >>> 15), 1 | t);
    r ^= r + Math.imul(r ^ (r >>> 7), 61 | r); return ((r ^ (r >>> 14)) >>> 0) / 4294967296; };
}
let _gmSky = null;
function gmLightsSVG() {
  if (_gmSky) return _gmSky;
  const hubs = GM_HUBS.map(([lat, lon, pull]) => ({ x: gmX(lon), y: gmY(lat), pull }));
  const rnd = gmRand(20260819);
  const out = [];
  for (let tries = 0; tries < 9000 && out.length < 1100; tries++) {
    const x = rnd() * GM_VIEW.w, y = rnd() * GM_VIEW.h;
    if (!gmInside(x, y)) continue;
    // brightness falls off with distance from the nearest population centre
    let best = 0;
    for (const h of hubs) {
      const d = Math.hypot(h.x - x, h.y - y);
      best = Math.max(best, h.pull / (1 + d * d / 90));
    }
    const lum = Math.min(1, best / 12);
    if (rnd() > 0.06 + lum * 0.94) continue;          // sparse where it is empty
    const r = (0.45 + lum * 1.15).toFixed(2);
    const o = (0.18 + lum * 0.75).toFixed(2);
    const warm = lum > 0.55;
    out.push(`<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${r}" fill="${warm ? '#ffd27a' : '#8fe3c2'}" opacity="${o}"/>`);
  }
  // a soft halo over the big cities, so clusters glow rather than just dot
  const halos = hubs.filter(h => h.pull >= 14).map(h =>
    `<circle cx="${h.x.toFixed(1)}" cy="${h.y.toFixed(1)}" r="${(h.pull * 0.9).toFixed(1)}" fill="url(#gm-glow)"/>`).join('');
  return (_gmSky = halos + out.join(''));
}

/* ── the run: a fixed map, no draws ───────────────────────────────────────── */
// Every club-season on the map is chosen in advance and never randomised, so
// each player runs the identical gauntlet and depth is comparable. Ratings are
// stored here (verified against the squad data) rather than computed at render.
//
//   3 rounds, choose 1 of 3  →  shop  →  3 rounds, choose 1 of 2  →  shop  →
//   two bosses, no choice.
const GM_RUN = [
  { kind: 'fight', round: 1, nodes: [
    { teamId: 'hapoel-aco',        season: '2009/10', ovr: 77, desc: 'עונת הבכורה בליגת העל - מקום 12 ומאבק הישרדות עד המחזור האחרון.' },
    { teamId: 'bnei-sakhnin',      season: '2007/08', ovr: 77, desc: 'מקום רביעי מפתיע עם 15 ניצחונות - מהעונות הגדולות של סכנין.' },
    { teamId: 'hapoel-hadera',     season: '2021/22', ovr: 78, desc: 'מקום 8 בעונה שבה מכבי חיפה לקחה אליפות - חדרה מבססת מקום בליגה.' },
  ] },
  { kind: 'fight', round: 2, nodes: [
    { teamId: 'hapoel-pt',         season: '2003/04', ovr: 79, desc: 'מקום 8 באמצע הטבלה; מנור חסן הוביל אותה עם 13 שערים.' },
    { teamId: 'bnei-yehuda',       season: '2005/06', ovr: 80, desc: 'מקום 4 עם 49 נקודות - בני יהודה של אמצע העשור.' },
    { teamId: 'maccabi-netanya',   season: '2007/08', ovr: 80, desc: 'סגנית האלופה: 58 נקודות ו-16 ניצחונות, מאחורי בית"ר בלבד.' },
  ] },
  { kind: 'fight', round: 3, nodes: [
    { teamId: 'ironi-ks',          season: '2010/11', ovr: 81, desc: 'מקום 5 בעונת הקיזוז - שנה אחת לפני האליפות ההיסטורית.' },
    { teamId: 'beitar-jerusalem',  season: '2001/02', ovr: 81, desc: 'עונה קשה במקום 10; מנור חסן כבש 11 מהשערים.' },
    { teamId: 'hapoel-haifa',      season: '2017/18', ovr: 82, desc: 'מקום 4 עם 62 נקודות - מהעונות הטובות של הפועל חיפה בעשור.' },
  ] },
  { kind: 'shop' },
  { kind: 'fight', round: 4, nodes: [
    { teamId: 'maccabi-pt',        season: '2003/04', ovr: 83, desc: 'מקום 3 עם 56 נקודות; עומר גולן כבש 13.' },
    { teamId: 'beitar-jerusalem',  season: '2017/18', ovr: 83, desc: 'מקום 3 עם 20 ניצחונות ו-68 נקודות.' },
  ] },
  { kind: 'fight', round: 5, nodes: [
    { teamId: 'beitar-jerusalem',  season: '2007/08', ovr: 84, desc: 'אלופה: 20 ניצחונות ו-67 נקודות.' },
    { teamId: 'maccabi-tlv',       season: '2002/03', ovr: 84, desc: 'אלופה עם 22 ניצחונות ורק 3 תיקו; אבי נמני כבש 14.' },
  ] },
  { kind: 'fight', round: 6, nodes: [
    { teamId: 'hapoel-beersheba',  season: '2014/15', ovr: 85, desc: 'מקום 3 עם 62 נקודות - העונה שלפני שושלת האליפויות.' },
    { teamId: 'hapoel-tlv',        season: '2009/10', ovr: 86, desc: 'עונת הדאבל: אליפות שהוכרעה בדקה ה-92 במחזור האחרון, וסיום ראשון בבית בליגה האירופית.' },
  ] },
  { kind: 'shop' },
  { kind: 'fight', round: 7, boss: true, nodes: [
    { teamId: 'maccabi-tlv',       season: '2015/16', ovr: 86, desc: '81 נקודות וסגנית - ערן זהבי כבש 35 שערים, שיא הליגה בעידן המודרני.' },
  ] },
  { kind: 'fight', round: 8, boss: true, nodes: [
    { teamId: 'maccabi-haifa',     season: '2001/02', ovr: 88, desc: 'אלופה 22-9-2 - והתואר הזה שלח אותה להיות הישראלית הראשונה בשלב הבתים של ליגת האלופות.' },
  ] },
];

/* ── layout: rows from the south up, measured off the silhouette ──────────── */
// Row positions are derived from the country itself rather than hardcoded: at a
// given height the land has a width, and a row only sits where its nodes fit
// inside it. The Negev is a spike, so the bottom rows ride further north on
// their own — no magic numbers to re-tune if the outline ever changes.
function gmSpanAt(y) {
  let lo = null, hi = null;
  for (let x = 0; x <= GM_VIEW.w; x += 1) {
    if (gmInside(x, y)) { if (lo === null) lo = x; hi = x; }
  }
  return lo === null ? null : { lo, hi };
}
function gmRowPositions(count, targetY, margin, climb = 400) {
  for (let y = targetY; y > targetY - climb && y > 50; y -= 5) {
    const span = gmSpanAt(y);
    if (!span) continue;
    const lo = span.lo + margin, hi = span.hi - margin;
    if (hi - lo < (count - 1) * (margin * 2.9)) continue;
    const xs = count === 1
      ? [(lo + hi) / 2]
      : Array.from({ length: count }, (_, i) => lo + ((hi - lo) * i) / (count - 1));
    if (xs.every(x => gmInside(x, y) && gmInside(x, y - margin) && gmInside(x, y + margin))) {
      return xs.map(x => ({ x, y }));
    }
  }
  const span = gmSpanAt(targetY) || { lo: 60, hi: 240 };
  const mid = (span.lo + span.hi) / 2;
  return Array.from({ length: count }, (_, i) => ({ x: mid + (i - (count - 1) / 2) * 34, y: targetY }));
}

// The lowest line the widest row can stand on. The Negev narrows to a spike, so
// a row of three simply cannot sit at the bottom of the map; asking each row to
// climb until it fits made the first three rows pile onto the same line.
function gmWidestRow() { return Math.max(...GM_RUN.map(r => r.kind === 'shop' ? 1 : r.nodes.length)); }
function gmBottomLine(margin = 17) {
  const n = gmWidestRow();
  for (let y = 700; y > 200; y -= 5) {
    const span = gmSpanAt(y);
    if (span && span.hi - span.lo - margin * 2 >= (n - 1) * margin * 2.9) return y;
  }
  return 560;
}

// laid out once: row 0 at the bottom, the final boss at the top
let _gmLayout = null;
function gmLayout() {
  if (_gmLayout) return _gmLayout;
  const rows = GM_RUN.length;
  const TOP = 90, BOTTOM = gmBottomLine();
  const gap = (BOTTOM - TOP) / (rows - 1);
  return (_gmLayout = GM_RUN.map((row, i) => {
    const y = BOTTOM - gap * i;
    const n = row.kind === 'shop' ? 1 : row.nodes.length;
    // a row may drift a little to find land, never far enough to touch its neighbour
    return gmRowPositions(n, y, row.kind === 'shop' ? 12 : 17, gap * 0.45);
  }));
}

// flat list of the fight rows, for the summary list under the map
function gmFightRows() { return GM_RUN.filter(r => r.kind === 'fight'); }

/* ── screen ───────────────────────────────────────────────────────────────── */
// A run in progress is one that has been started, whether or not a fight has
// been fought — so the explainer shows once, not after every defeat.
function gtRunStarted(run) { return !!(run.started || run.log.length || run.picks); }

function gmIntroHTML() {
  const best = typeof gtBest === 'function' ? gtBest() : { depth: 0 };
  const office = typeof gtManagerPickerHTML === 'function' ? gtManagerPickerHTML() : '';
  // the signature-relic line is a promise, so it only appears once there is
  // actually a front office to hire from
  const sigLine = office
    ? ' קמע חתימה אחד (של המנג׳ר שבחרת) נעול איתך עד סוף המסע ולא תופס מקום.' : '';
  return `
    <div class="gt-intro">
      <div class="gt-intro-title">🗺 מסע הגאונטלט</div>
      ${best.depth ? `<p class="gt-intro-best">🏅 השיא שלך: <b>${best.depth}</b> ניצחונות${best.cleared ? ' · המסע הושלם' : ''}${best.banner ? ' · ' + gtBannerName(best.banner) : ''}</p>` : ''}
      <p>שמונה קרבות מדרום לצפון, מול סגלים אמיתיים מההיסטוריה של ליגת העל - מקבוצה שנאבקה על הישרדות ועד השושלות הגדולות ביותר בכדורגל הישראלי.</p>
      <ul class="gt-intro-list">
        <li>📜 <b>פותחים בקמע מסע</b> - אחד מששה, לכל אחד יתרון ומחיר, ומלווה אותך עד הסוף. אפשר גם בלי.</li>
        <li>🎲 <b>מגרילים קבוצה ובוחרים שחקן</b> - פעם אחת בתחילת המסע, וההרכב הזה מלווה אותך עד הסוף.</li>
        <li>⚽ <b>בכל משחק אתה בוחר את היריבה</b> מבין האפשרויות שנפתחו - ואי אפשר להתחרט.</li>
        <li>💜 <b>בכל סיבוב אחת היריבות מסומנת ELITE</b> - חזקה יותר, אבל השלל שלה מפיל קמעות הרבה יותר.</li>
        <li>🎰 <b>ניצחת? מסתובב גלגל השלל</b> - עליו גם שחקנים מהסגל שהבסת וגם <b>קמעות</b>, ואף פעם אין חובה לקחת.</li>
        <li>🛒 <b>כל 3 קרבות נפתחת חנות</b> - מטבעות מניצחונות, ועליהם ריבית.</li>
        <li>⏸ <b>מפגר במחצית?</b> אפשר לפרוק הכול על 45 הדקות הבאות - במחיר ויתור על השלל.</li>
        <li>🥇 <b>שני הבוסים האחרונים</b> משוחקים בשני משחקים - חוץ ובית, מאזן מצטבר.</li>
        <li>💀 <b>הפסד אחד מסיים את הריצה.</b></li>
        <li>🏴 <b>סיימת את כל השמונה?</b> מניפים באנר ורצים שוב - כל היריבות מתחזקות.</li>
      </ul>
      <div class="gt-intro-relic">
        <div class="gt-intro-relic-t">🔮 מה זה קמע?</div>
        <p>חפץ שמשנה כלל אחד במשחק - למשל קהל בית שמחזק אותך בקרבות מסוימים, ניצחון מובטח בפנדלים, הצצה לדירוג היריבה הבאה, או החתמת שחקן בלי הגרלה. בחירה נכונה שווה יותר משחקן טוב אחד.</p>
        <p><b>יש לך 5 מקומות לקמעות.</b> כשהם מלאים וזוכים בעוד אחד - צריך להחליט: להחליף אותו באחד מהקיימים, או לוותר עליו.${sigLine}</p>
      </div>
      ${office}
      <button class="btn-primary btn-full" id="gt-begin">יאללה, מתחילים ←</button>
    </div>`;
}

function showGauntlet() {
  showScreen('gauntlet');
  const back = document.getElementById('gauntlet-back');
  if (back) back.onclick = () => showScreen('welcome');

  const run = typeof gtRun === 'function' ? gtRun() : { at: 0, log: [], over: false };
  const map = document.getElementById('gauntlet-map');
  const note = document.getElementById('gauntlet-note');
  const reset = document.getElementById('gauntlet-reset');

  // first visit (or a fresh run): explain the mode before showing the map
  if (!gtRunStarted(run)) {
    map.innerHTML = gmIntroHTML();
    if (note) note.textContent = '';
    if (reset) reset.style.display = 'none';
    if (typeof gtWireManagerPicker === 'function') {
      gtWireManagerPicker(map, () => { run.started = true; gtSave(); showGauntlet(); });
    }
    const go = document.getElementById('gt-begin');
    if (go) go.onclick = () => {
      // with a front office in play, hiring is the first decision of the run
      if (typeof gtManagersEnabled === 'function' && gtManagersEnabled() && !run.managerId) {
        const office = map.querySelector('.gt-office');
        if (office) { office.classList.add('needed'); office.scrollIntoView({ behavior: 'smooth' }); return; }
      }
      run.started = true; gtSave(); showGauntlet();
    };
    return;
  }
  if (reset) {
    reset.style.display = '';
    reset.onclick = () => { if (typeof gtReset === 'function') gtReset(); showGauntlet(); };
  }

  // The run opens on a bargain: one run rule, or none, before the first road is
  // even on screen.
  if (typeof gtNeedsMod === 'function' && gtNeedsMod()) {
    map.innerHTML = gtModPickerHTML();
    if (note) note.textContent = '';
    if (reset) reset.style.display = 'none';   // nothing has happened yet to reset
    gtWireModPicker(map, () => showGauntlet());
    return;
  }

  // The squad has to be in memory whenever this screen draws: the shop spends it,
  // and the bar prints its rating.
  if (run.picks && typeof gtRestoreSquad === 'function') {
    gtRestoreSquad();
    if (typeof gtInvalidateDeltas === 'function') gtInvalidateDeltas();
  }

  renderGauntletMap(map, run.at, !!run.over);
  if (typeof gtWireRelicBar === 'function') gtWireRelicBar(map);
  if (typeof gtWireShop === 'function' && map.querySelector('.gt-shop')) gtWireShop(map);
  if (typeof gtWireVictory === 'function' && map.querySelector('.gt-victory')) gtWireVictory(map);
  const newRun = map.querySelector('#gt-new-run');
  if (newRun) newRun.onclick = () => { gtReset(); showGauntlet(); };

  // the sandbox, for one account
  if (typeof gtAdminHTML === 'function') {
    const panel = gtAdminHTML();
    if (panel) {
      const host = document.createElement('div');
      host.innerHTML = panel;
      map.appendChild(host);
      gtWireAdmin(host);
    }
  }

  const choose = el => {
    if (typeof gtChoose === 'function') gtChoose(+el.dataset.row, +el.dataset.node);
  };
  map.querySelectorAll('.gm-station.next[data-row]').forEach(g => g.addEventListener('click', () => choose(g)));
  map.querySelectorAll('.gm-road[data-row]').forEach(b => b.addEventListener('click', () => choose(b)));

  if (note) {
    const cleared = (run.log || []).filter(l => l.outcome === 'W').length;
    note.textContent = run.over
      ? `הריצה נגמרה אחרי ${cleared} ניצחונות.`
      : cleared ? `עברת ${cleared} מתוך 8.` : '';
  }
}
