/* ── מצב סיפור: screens ───────────────────────────────────────────────────────
 *
 * Four things, all rendered into existing surfaces:
 *   · the hub — the chapter cards (screen-story)
 *   · the market — the same renderer for summer (screen-story) and January (an
 *     overlay over the reveal, the way js/january.js opens its window)
 *   · the verdict — a box on the results screen (#story-end-box)
 * Colours come from the app's tokens only. This is a #0d1117 app.
 */
(function (global) {
  'use strict';

  const esc = s => String(s == null ? '' : s).replace(/[&<>"]/g,
    c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  // "3.6 מ׳" — the shekel sign glued to a number flips around it in RTL
  // ("מ׳3.6₪"), and a budget screen already says what currency it is in.
  // Money is thousands of ₪: 2500 → "2.5 מיליון", 350 → "350 אלף". No shekel sign —
  // glued to a number it flips around it in RTL, and the screen says what it is in.
  const money = n => n >= 1000
    ? `<bdi dir="ltr">${String(Math.round(n / 10) / 100)}</bdi> מיליון`
    : `<bdi dir="ltr">${Math.round(n)}</bdi> אלף`;
  const num = n => `<bdi dir="ltr">${n}</bdi>`;
  // What you type is whole shekels, with separators: "1,500,000". The owner could
  // not tell what "1500" in a box marked "אלף" meant; nobody misreads a full sum.
  const shekels = k => (Math.round(k) * 1000).toLocaleString('en-US');
  const parseK = str => Math.round((Number(String(str).replace(/[^\d]/g, '')) || 0) / 1000);
  const amountBox = (attr, k) => `<span class="st-amtw"><input class="st-amt" ${attr} type="text"
    inputmode="numeric" dir="ltr" value="${shekels(k)}"><span class="st-unit">₪</span></span>`;
  // Keeps the box readable as you type, and says the sum back in words.
  function wireAmount(inp, sayEl) {
    const sync = () => {
      const k = parseK(inp.value);
      inp.value = k ? shekels(k) : '';
      if (sayEl) sayEl.innerHTML = k ? `ההצעה שלך: <b>${money(k)} ₪</b>` : '';
    };
    inp.addEventListener('input', () => {
      const k = parseK(inp.value);
      if (sayEl) sayEl.innerHTML = k ? `ההצעה שלך: <b>${money(k)} ₪</b>` : '';
    });
    inp.addEventListener('blur', sync);
    sync();
  }
  const clubName = id => (typeof TEAMS !== 'undefined' && TEAMS[id] && TEAMS[id].name) || id;
  // A club's crest from /crests (Israeli, by teamId) or /crests/eu (European,
  // by the club's `crest`), and nothing at all when the file is missing.
  const crestImg = (id, eu, cls) => id ? `<img class="st-crest ${cls || ''}" alt="" loading="lazy"
    src="crests/${eu ? 'eu/' : ''}${esc(id)}.png" onerror="this.remove()">` : '';
  const oppMark = c => c.crest ? crestImg(c.crest, true) : (c.flag || '');
  // The words of a chapter, editable in admin.html ("מצב סיפור") without code:
  // keys sm-<chapter>-<field>, generated by scripts/sync_story_texts.js.
  const storyT = (ch, field, def) => (typeof siteText === 'function' ? siteText(`sm-${ch.id}-${field}`, def) : def);
  const titleOf = ch => storyT(ch, 'title', ch.title);
  const starLabel = (ch, i) => storyT(ch, 'star' + (i + 1), ch.stars[i].label);
  const realTextOf = ch => storyT(ch, 'real', ch.europe.realText);
  const posHe = p => (typeof POS_HE !== 'undefined' && POS_HE[p]) || p;

  function ensureStyle() {
    if (document.getElementById('story-style')) return;
    const s = document.createElement('style');
    s.id = 'story-style';
    s.textContent = `
.st-cards{display:grid;gap:12px}
.st-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);
  padding:16px;text-align:right;color:var(--text);font-family:inherit;cursor:pointer;width:100%}
.st-card:hover{background:var(--hover)}
.st-card h3{margin:0 0 4px;font-size:18px}
.st-card .st-meta{color:var(--dim);font-size:13px}
.st-stars{color:var(--accent);letter-spacing:2px;font-size:16px}
.st-stars .off{color:var(--border)}
.st-intro{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);
  padding:16px;margin:0 0 14px;line-height:1.7}
.st-goals{margin:10px 0 0;padding:0;list-style:none;font-size:14px}
.st-goals li{margin:3px 0}
.st-bar{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 12px}
.st-chip{flex:1;min-width:92px;background:var(--surface);border:1px solid var(--border);
  border-radius:9px;padding:8px;text-align:center}
.st-chip i{display:block;font-style:normal;font-size:11px;color:var(--dim)}
.st-chip b{font-size:18px}
.st-row{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 12px}
.st-row select,.st-row input{flex:1;min-width:120px;background:var(--surface);color:var(--text);
  border:1px solid var(--border);border-radius:8px;padding:8px;font-family:inherit}
.st-h{font-size:14px;color:var(--dim);margin:14px 0 6px}
.st-list{display:flex;flex-direction:column;gap:6px}
.st-p{display:flex;align-items:center;gap:8px;background:var(--surface);border:1px solid var(--border);
  border-radius:9px;padding:8px 10px}
.st-p.xi{border-color:var(--accent)}
.st-p .n{flex:1;min-width:0}
.st-p .n b{display:block;font-size:14px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.st-p .n em{font-style:normal;font-size:12px;color:var(--dim)}
.st-p .o{font-weight:700;font-size:17px;width:30px;text-align:center}
.st-b{background:var(--panel);color:var(--text);border:1px solid var(--border);border-radius:8px;
  padding:7px 10px;font-family:inherit;font-size:13px;cursor:pointer;white-space:nowrap}
.st-b:hover{background:var(--hover)}
.st-b.go{background:var(--accent);color:var(--accent-ink);border-color:var(--accent);font-weight:700}
.st-b[disabled]{opacity:.45;cursor:default}
.st-msg{min-height:20px;color:var(--accent);font-size:13px;margin:6px 0}
.st-go{width:100%;padding:13px;font-size:16px;margin:14px 0 4px}
.st-wrap{position:fixed;inset:0;z-index:9000;overflow-y:auto;background:rgba(0,0,0,.78);padding:16px}
.st-box{background:var(--panel);border:1px solid var(--border);border-radius:var(--radius);
  max-width:560px;margin:0 auto;padding:18px}
.st-end{background:var(--surface);border:1px solid var(--accent);border-radius:var(--radius);
  padding:16px;margin:14px 0;text-align:center}
.st-end .st-stars{font-size:28px}
.st-vs{display:flex;gap:8px;margin:12px 0}
.st-vs div{flex:1;background:var(--panel);border:1px solid var(--border);border-radius:9px;padding:8px}
.st-vs i{display:block;font-style:normal;font-size:11px;color:var(--dim)}
.st-kick{color:var(--accent);margin:0 0 6px;font-weight:600}
.st-note{margin:0 0 10px;color:var(--dim);font-size:13px}
.st-group{margin:0 0 10px}
.st-gh{font-size:13px;color:var(--dim);margin:10px 0 5px}
.st-gh b{color:var(--text);font-size:14px}
.st-short{color:#f85149;font-weight:700}
.st-empty{color:var(--dim);font-size:13px;padding:4px 2px}
.st-tag{display:inline-block;font-size:11px;border:1px solid var(--border);border-radius:6px;
  padding:0 5px;margin-inline-start:4px;color:var(--accent)}
.st-bid{background:var(--surface);border:1px solid var(--accent);border-radius:9px;padding:9px 10px;font-size:14px}
.st-btns{display:flex;flex-wrap:wrap;gap:6px;align-items:center;margin-top:7px}
.st-quick .st-b{font-size:12px;padding:5px 8px}
.st-talk{background:var(--panel);border:1px solid var(--border);border-top:none;
  border-radius:0 0 9px 9px;margin:-4px 0 0;padding:10px}
.st-say{font-size:14px;margin:0 0 4px}
.st-amt{width:96px;background:var(--surface);color:var(--text);border:1px solid var(--border);
  border-radius:8px;padding:7px;font-family:inherit;font-size:14px}
.st-unit{font-size:13px;color:var(--dim)}
.st-hurt{color:#f85149}
.st-tag.no{color:#f85149;border-color:#f8514966}
.st-chk{display:flex;align-items:center;gap:5px;font-size:13px;color:var(--dim);white-space:nowrap}
.lu{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:10px 12px;margin:0 0 12px}
.lu>summary{cursor:pointer;font-weight:700;color:var(--accent)}
.lu-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:6px;margin:10px 0 4px}
.lu-row{display:flex;align-items:center;gap:6px;font-size:13px}
.lu-row span{min-width:70px;color:var(--dim)}
.lu-row select{flex:1;min-width:0;background:var(--panel);color:var(--text);border:1px solid var(--border);border-radius:7px;padding:5px;font-family:inherit}
.st-crest{width:22px;height:22px;object-fit:contain;vertical-align:middle;margin-inline-end:6px}
.st-crest.big{width:34px;height:34px}
.eu-road{display:flex;flex-wrap:wrap;gap:6px;margin:0 0 12px}
.eu-step{font-size:12px;border:1px solid var(--border);border-radius:14px;padding:3px 9px;color:var(--dim)}
.eu-step.ok{color:#3fb950;border-color:#3fb95066}
.eu-step.out{color:#f85149;border-color:#f8514966}
.eu-step.now{color:var(--accent);border-color:var(--accent);font-weight:700}
.eu-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:14px;margin:0 0 12px}
.eu-card.last{border-color:var(--accent)}
.eu-card h3{margin:0 0 10px;font-size:17px}
.eu-leg{background:var(--panel);border:1px solid var(--border);border-radius:9px;padding:8px 10px;margin:0 0 6px}
.eu-leg b{display:block;font-size:15px}
.eu-leg span{font-size:12px;color:var(--dim)}
.eu-leg em{display:block;font-style:normal;font-size:12px;color:var(--dim);margin-top:3px}
.eu-leg.w{border-inline-start:3px solid #3fb950}.eu-leg.l{border-inline-start:3px solid #f85149}.eu-leg.d{border-inline-start:3px solid var(--dim)}
.eu-next{margin:10px 0 4px;font-weight:600}
.eu-need{margin:4px 0;color:var(--accent);font-weight:700}
.eu-verdict{font-size:17px;font-weight:700;margin:8px 0 4px}
.eu-verdict.ok{color:#3fb950}.eu-verdict.out{color:#f85149}
.eu-tac{display:flex;gap:6px;margin:12px 0 0}
.eu-tac .st-b{flex:1;display:flex;flex-direction:column;align-items:center;gap:2px;padding:9px 4px}
.eu-tac small{font-size:11px;opacity:.85}
.eu-tbl{width:100%;border-collapse:collapse;font-size:13px;margin:4px 0 8px}
.eu-tbl th{color:var(--dim);font-weight:400;text-align:right;padding:3px 4px}
.eu-tbl td{padding:4px;border-top:1px solid var(--border)}
.eu-tbl tr.us td{color:var(--accent);font-weight:700}
.st-amtw{display:inline-flex;align-items:center;gap:5px}
.st-amt{width:130px}
.st-amtsay{font-size:13px;color:var(--dim);min-height:18px;margin-top:4px}
`;
    document.head.appendChild(s);
  }

  function starsHTML(arr) {
    return `<span class="st-stars">${[0, 1, 2].map(i =>
      `<span class="${arr && arr[i] ? '' : 'off'}">★</span>`).join('')}</span>`;
  }
  function root() { return document.getElementById('story-root'); }

  /* ── the hub ─────────────────────────────────────────────────────────────── */
  function storyShowHub() {
    ensureStyle();
    showScreen('story');
    if (typeof storyTrack === 'function') storyTrack('open');
    const back = document.getElementById('story-back');
    if (back) back.onclick = () => showScreen('setup');
    const best = storyBest();
    const run = storyRun();
    root().innerHTML = `
      <p class="st-meta" style="color:var(--dim);margin:0 0 14px">${esc(typeof siteText === 'function'
        ? siteText('sm-hub-blurb', 'רגעים אמיתיים מתולדות ליגת העל. אתה המועדון, עם הסגל והקופה של אותה עונה. תגיע למטרה, ואז תנסה לעקוף את המציאות.')
        : '')}</p>
      <div class="st-cards">${STORY_CHAPTERS.filter(ch => !ch.hidden).map(ch => {
        const real = storyReal(ch);
        const b = best[ch.id];
        const live = run && run.chapterId === ch.id && run.phase !== 'done';   // summer, season, jan or europe
        return `<button class="st-card" data-ch="${ch.id}">
          <h3>${crestImg(ch.teamId)}${esc(clubName(ch.teamId))} ${esc(ch.season)}: ${esc(titleOf(ch))}</h3>
          <div class="st-meta">${ch.kind === 'europe' ? `${esc(ch.comp)} · במציאות: ${esc(realTextOf(ch))}`
            : `במציאות: מקום ${real ? real.pos : '?'}, ${real ? real.pts : '?'} נק׳`}
            ${b ? ` · השיא שלך: ${num(b.score)}` : ''}${live ? ' · <b style="color:var(--accent)">בתהליך</b>' : ''}</div>
          ${starsHTML(b && b.stars)}
        </button>`;
      }).join('')}</div>`;
    root().querySelectorAll('.st-card').forEach(el => {
      el.onclick = () => storyShowIntro(el.dataset.ch);
    });
  }

  function storyShowIntro(chId) {
    const ch = storyChapter(chId);
    const run = storyRun();
    const live = run && run.chapterId === ch.id && run.phase === 'summer';
    const inEurope = run && run.chapterId === ch.id && run.eu && ['europe', 'jan', 'done'].includes(run.phase);
    if (inEurope) { storyShowEurope(); return; }
    const real = storyReal(ch);
    root().innerHTML = `
      <div class="st-intro">
        <h3 style="margin:0 0 8px">${crestImg(ch.teamId, false, 'big')}${esc(clubName(ch.teamId))} ${esc(ch.season)}: ${esc(titleOf(ch))}</h3>
        <p style="margin:0">${esc(storyT(ch, 'intro', ch.intro))}</p>
        <ul class="st-goals">${ch.stars.map((s, i) =>
          `<li>${'★'.repeat(i + 1)} ${esc(starLabel(ch, i))}${s.type === 'beatPoints' && real ? ` (${real.pts})` : ''}</li>`).join('')}</ul>
        <p class="st-meta" style="color:var(--dim);margin:10px 0 0">תקציב פתיחה: ${money(ch.budget)} ·
          עד ${storyRules(ch).buys.summer} רכישות בקיץ ו-${storyRules(ch).buys.jan} בינואר ·
          סגל של ${storyRules(ch).minSquad} שחקנים לפחות</p>
      </div>
      <button class="st-b go st-go" id="st-begin">${live ? 'להמשיך את הקיץ' : 'להתחיל את הפרק'}</button>
      <button class="st-b st-go" id="st-hub">חזרה לפרקים</button>`;
    document.getElementById('st-begin').onclick = () => live ? storyShowMarket('summer') : storyStart(ch.id);
    document.getElementById('st-hub').onclick = storyShowHub;
  }

  /* ── the market (both windows) ───────────────────────────────────────────── */
  // ctx: { run, ch, window: 'summer'|'jan', statOf(name) → stats|null, host, persist?, onDone,
  //        q, pos — the market filters; open — the player being negotiated; msg }
  //
  // Nothing here has a price tag. Buying is a negotiation with the selling club
  // (storyOffer); selling is putting a player on the market and answering the
  // bids that come (storyListPlayer / storyCourt). The squad is grouped by
  // position with a count against what the shape needs.
  function renderMarket(ctx) {
    const { run, ch } = ctx;
    const jan = ctx.window === 'jan';
    const keyOf = e => e.squad.id + '|' + e.player.name;
    const ownKeys = new Set(run.own.map(r => r.squadId + '|' + r.name));
    const mine = e => ownKeys.has(keyOf(e));
    // Your own players are priced by what they did (January); everyone else by name.
    const valueOf = e => jan
      ? (mine(e) ? storyJanValue(e.player, ctx.statOf(e.player.name)) : storyValueOfOvr(e.player.ovr))
      : storySummerValue(e.player, ch.season);
    const owned = storyOwned(run).sort((a, b) => b.player.ovr - a.player.ovr);

    // Clubs come for the men who are making news: January's performers, and in
    // summer the ones who arrived with last season's goals behind them.
    const courted = e => jan
      ? storyPerfBonus(e.player.position, ctx.statOf(e.player.name)) >= 3
      : storySummerValue(e.player, ch.season) > storyValueOfOvr(e.player.ovr);
    const fresh = storyCourt(run, ch, owned, valueOf, courted);
    if (fresh.length && ctx.persist) ctx.persist();

    const slots = formationSlots(run.formationId, run.tactic);
    const when = ctx.when || null;
    const lineup = storyLineup(run, when);
    const xiNames = new Set(lineup.picks.filter(Boolean).map(e => e.player.name));
    const hurt = new Set(storyInjured(run, when).map(e => e.player.name));
    const hurtWhen = !when ? '' : when === 'h1' ? 'יחמיץ את החצי הראשון' : when === 'h2' ? 'יחמיץ את החצי השני' : 'יחמיץ את המשחק הבא';
    const needs = storyGroupNeeds(slots);
    const left = storyRules(ch).buys[ctx.window] - run.buys[ctx.window];
    const tactical = formationTactical(run.formationId);
    const bids = storyLiveOffers(run);

    // the market list: what you can afford first, then the best of what you cannot
    const q = (ctx.q || '').trim();
    const pos = ctx.pos || '';
    const askOf = e => storyAsk(run, ch, e, valueOf(e));
    const found = storyMarketPool(run, ch)
      .filter(e => (!q || e.player.name.includes(q) || clubName(e.squad.teamId).includes(q)) &&
                   (!pos || e.player.position === pos))
      .sort((a, b) => b.player.ovr - a.player.ovr);
    // One list, by rating, highest first. "רק מה שבתקציב" (on by default) hides
    // whoever you cannot afford or cannot have; the old split — affordable first,
    // then the rest — read as a list that was simply out of order.
    const fits = e => { const a = askOf(e); return !a.notForSale && a.ask <= run.budget; };
    const onlyAfford = ctx.afford !== false;
    const pool = (onlyAfford ? found.filter(fits) : found).slice(0, 40);
    const positions = [...new Set(storyMarketPool(run, ch).map(e => e.player.position))].sort();

    const statLine = e => {
      const st = jan ? ctx.statOf(e.player.name) : null;
      return st ? ` · ${st.goals} ש׳ ${st.assists} ב׳${st.cs ? ` ${st.cs} נקיים` : ''}` : '';
    };
    const playerRow = (e, right) => `
      <div class="st-p${xiNames.has(e.player.name) ? ' xi' : ''}">
        <span class="o">${e.player.ovr}</span>
        <span class="n"><b>${esc(e.player.name)}</b><em>${esc(posHe(e.player.position))}${statLine(e)}${
          hurt.has(e.player.name) ? ` · <span class="st-hurt">🩹 ${hurtWhen}</span>` : ''}</em></span>
        ${right}</div>`;

    // ── bids on your players
    const bidsHTML = bids.length ? `
      <div class="st-h">הצעות על השחקנים שלך</div>
      <div class="st-list">${bids.map(o => `
        <div class="st-bid">
          <div><b>${esc(storyBidderName(o.club))}</b> מציעה <b>${money(o.amount)} ₪</b> על ${esc(o.name)}
            ${o.unsolicited ? '<span class="st-tag">פנייה יזומה</span>' : ''}
            ${o.round ? `<span class="st-tag">נשארו ${STORY_RULES.bidRounds - o.round} בקשות</span>` : ''}</div>
          <div class="st-btns">
            <button class="st-b go" data-bid-ok="${esc(o.id)}">לקבל ${money(o.amount)} ₪</button>
            <button class="st-b" data-bid-no="${esc(o.id)}">לדחות</button>
          </div>
          <div class="st-btns">
            ${amountBox(`data-bid-amt="${esc(o.id)}"`, storyK(o.amount * 1.15))}
            <button class="st-b" data-bid-more="${esc(o.id)}">לבקש את הסכום</button>
          </div>
          <div class="st-amtsay" data-bid-say="${esc(o.id)}"></div></div>`).join('')}</div>` : '';

    // ── the squad, by position
    const squadHTML = STORY_GROUPS.map(g => {
      const inG = owned.filter(e => storyGroupOf(e.player.position) === g.id);
      const need = needs[g.id];
      const short = inG.length < need;
      return `<div class="st-group">
        <div class="st-gh"><b>${g.label}</b> <span>${inG.length} בסגל</span>
          ${need ? `<span class="${short ? 'st-short' : ''}">· המערך צריך ${need}</span>` : ''}</div>
        <div class="st-list">${inG.map(e => {
          const n = bids.filter(o => o.squadId === e.squad.id && o.name === e.player.name).length;
          return playerRow(e, n
            ? `<span class="st-tag">${n === 1 ? 'הצעה אחת' : n + ' הצעות'} ↑</span>`
            : `<button class="st-b" data-list="${esc(keyOf(e))}">להציע למכירה</button>`);
        }).join('') || '<div class="st-empty">אין</div>'}</div></div>`;
    }).join('');

    // ── the market, and the one negotiation that is open
    const talkHTML = e => {
      const t = storyTalk(run, ch, e, valueOf(e));
      const lastLine = ctx.talkMsg && ctx.open === keyOf(e) ? `<div class="st-say">${ctx.talkMsg}</div>` : '';
      if (t.nfs) return `<div class="st-talk"><div class="st-say">${esc(clubName(e.squad.teamId))}: "הוא לא למכירה. לא משנה כמה."</div></div>`;
      const roundsLeft = STORY_RULES.talkRounds - t.round;
      // What you last typed survives the redraw that every answer causes. It used
      // to snap back to 85% of the ask, so an offer the club refused — or one the
      // budget blocked — looked like the box had simply reset itself.
      const dflt = ctx.amt != null ? ctx.amt : storyK(t.ask * 0.85);
      return `<div class="st-talk">
        ${lastLine}
        <div class="st-say">${esc(clubName(e.squad.teamId))} ${t.round ? 'עומדת על' : 'מבקשת'} <b>${money(t.ask)} ₪</b>
          ${t.closed ? '' : `· נשארו ${roundsLeft} הצעות`}</div>
        ${t.closed && !t.lastCounter ? '' : `
        <div class="st-btns">
          ${t.closed ? '' : `${amountBox('id="st-amt"', dflt)}
          <button class="st-b go" data-offer="${esc(keyOf(e))}">להגיש הצעה</button>`}
          ${t.lastCounter ? `<button class="st-b go" data-take="${esc(keyOf(e))}">לקבל ${money(t.ask)} ₪</button>` : ''}
        </div>
        ${t.closed ? '' : `<div class="st-amtsay" id="st-amt-say"></div>
        <div class="st-btns st-quick">
          ${[0.7, 0.8, 0.9].map(f => `<button class="st-b" data-quick="${storyK(t.ask * f)}">${Math.round(f * 100)}% · ${money(storyK(t.ask * f))}</button>`).join('')}
        </div>`}`}
      </div>`;
    };
    const marketHTML = pool.map(e => {
      const a = askOf(e);
      const nfs = { top: 'לא למכירה', symbol: 'סמל: לא יעבור ליריבה', refuse: 'מסרב לעבור ליריבה' }[a.why] || '';
      const tags = [a.derby ? 'דרבי' : (a.rival ? 'יריבה' : ''), a.symbol ? 'סמל' : '', a.key ? 'שחקן מפתח' : '', nfs]
        .filter(Boolean).map(s => `<span class="st-tag${s === nfs ? ' no' : ''}">${s}</span>`).join('');
      const k = keyOf(e);
      const open = ctx.open === k;
      return `<div class="st-mkt">
        <div class="st-p">
          <span class="o">${e.player.ovr}</span>
          <span class="n"><b>${esc(e.player.name)}</b><em>${esc(posHe(e.player.position))} ·
            ${esc(clubName(e.squad.teamId))}${a.notForSale ? '' : ` · ${money(a.ask)} ₪`} ${tags}</em></span>
          <button class="st-b" data-talk="${esc(k)}"${a.notForSale || left <= 0 ? ' disabled' : ''}>
            ${open ? 'לסגור' : 'מו״מ'}</button>
        </div>${open ? talkHTML(e) : ''}</div>`;
    }).join('');

    ctx.host.innerHTML = `
      <p class="st-kick">${jan ? 'חלון ההעברות של ינואר' : 'חלון ההעברות של הקיץ'} · ${esc(clubName(ch.teamId))} ${esc(ch.season)}</p>
      ${jan ? `<p class="st-note">הערך של השחקנים שלך מתעדכן לפי מה שעשו בחצי העונה, ומי שהופיע מושך הצעות.</p>` : ''}
      <div class="st-bar">
        <div class="st-chip"><i>תקציב</i><b>${money(run.budget)} ₪</b></div>
        <div class="st-chip"><i>רכישות שנשארו</i><b>${left}</b></div>
        <div class="st-chip"><i>סגל</i><b>${run.own.length}</b></div>
        <div class="st-chip"><i>דירוג ההרכב</i><b>${lineup.ovr}</b></div>
      </div>
      <div class="st-row">
        <select id="st-form">${Object.keys(FORMATIONS).map(k =>
          `<option value="${k}"${k === run.formationId ? ' selected' : ''}>${esc(FORMATIONS[k].label)}</option>`).join('')}</select>
        <select id="st-tac"${tactical ? '' : ' disabled'}>${TACTIC_KEYS.map(k =>
          `<option value="${k}"${k === run.tactic ? ' selected' : ''}>${esc(TACTICS[k].label)}</option>`).join('')}</select>
      </div>
      <div class="st-msg" id="st-msg">${ctx.msg || ''}</div>
      ${bidsHTML}
      ${lineupHTML(run, lineup, hurt)}
      <div class="st-h">הסגל שלך. ההרכב במסגרת צהובה</div>
      ${squadHTML}
      <div class="st-h">השוק. לחץ "מו״מ" כדי לפתוח משא ומתן עם המועדון</div>
      <div class="st-row">
        <input id="st-q" placeholder="חיפוש שחקן או מועדון" value="${esc(q)}">
        <label class="st-chk"><input type="checkbox" id="st-afford"${onlyAfford ? ' checked' : ''}> רק מה שבתקציב</label>
        <select id="st-pos"><option value="">כל העמדות</option>${positions.map(p =>
          `<option value="${p}"${p === pos ? ' selected' : ''}>${esc(posHe(p))}</option>`).join('')}</select>
      </div>
      <div class="st-list">${marketHTML}</div>
      <button class="st-b go st-go" id="st-done">${ctx.doneLabel || (jan ? 'להמשיך את העונה' : 'לפתיחת העונה')}</button>`;

    // Scoped on purpose: January renders into an overlay while the summer market
    // is still in the (hidden) story screen with the same ids, and a page-wide
    // lookup finds the summer copy first — "להמשיך את העונה" did nothing.
    const byId = id => ctx.host.querySelector('#' + id);
    const redraw = extra => renderMarket({ ...ctx, ...extra });
    // "Not enough budget" alone read as nothing happening; say what there is.
    const blockedMsg = why => /תקציב/.test(why)
      ? `${esc(why)}: יש לך ${money(run.budget)} ₪. ההצעה לא נשלחה.`
      : esc(why);
    const saved = () => { if (ctx.persist) ctx.persist(); };
    wireLineup(ctx.host, run, lineup, () => { saved(); redraw({ msg: '' }); });
    const byKey = k => [...owned, ...pool].find(e => keyOf(e) === k);
    const $ = sel => ctx.host.querySelectorAll(sel);

    $('[data-list]').forEach(b => b.onclick = () => {
      const e = byKey(b.dataset.list);
      const made = storyListPlayer(run, ch, e, valueOf(e));
      saved();
      redraw({ msg: made.length
        ? `${esc(e.player.name)} בשוק: ${made.length === 1 ? 'הגיעה הצעה אחת' : `הגיעו ${made.length} הצעות`}`
        : `אף מועדון לא הציע על ${esc(e.player.name)}` });
    });
    $('[data-bid-ok]').forEach(b => b.onclick = () => {
      const o = bids.find(x => x.id === b.dataset.bidOk);
      const why = storyAcceptBid(run, o.id);
      saved();
      redraw({ msg: why ? esc(why) : `${esc(o.name)} נמכר ל${esc(storyBidderName(o.club))} ב-${money(o.amount)} ₪` });
    });
    $('[data-bid-no]').forEach(b => b.onclick = () => {
      storyRejectBid(run, b.dataset.bidNo);
      saved();
      redraw({ msg: 'ההצעה נדחתה' });
    });
    $('[data-bid-more]').forEach(b => b.onclick = () => {
      const o = bids.find(x => x.id === b.dataset.bidMore);
      const inp = ctx.host.querySelector(`[data-bid-amt="${o.id}"]`);
      const club = esc(storyBidderName(o.club));
      const r = storyPushBid(run, o.id, parseK(inp && inp.value));
      saved();
      redraw({ msg: r.kind === 'accept' ? `${club} הסכימה: ${esc(o.name)} נמכר ב-${money(r.amount)} ₪`
        : r.kind === 'counter' ? `${club}: "לא בסכום הזה. אנחנו מעלים ל-${money(r.amount)} ₪."`
        : r.kind === 'walk' ? `${club} ירדה מהעסקה`
        : esc(r.why) });
    });
    $('[data-talk]').forEach(b => b.onclick = () => {
      const k = b.dataset.talk;
      redraw({ open: ctx.open === k ? null : k, talkMsg: '', msg: '', amt: null });
    });
    $('[data-quick]').forEach(b => b.onclick = () => {
      const inp = byId('st-amt');
      if (inp) { inp.value = shekels(Number(b.dataset.quick)); inp.dispatchEvent(new Event('blur')); }
    });
    const amt = byId('st-amt');
    if (amt) wireAmount(amt, byId('st-amt-say'));
    $('[data-bid-amt]').forEach(inp => wireAmount(inp, ctx.host.querySelector(`[data-bid-say="${inp.dataset.bidAmt}"]`)));
    $('[data-offer]').forEach(b => b.onclick = () => {
      const e = byKey(b.dataset.offer);
      const amount = parseK(byId('st-amt').value);
      const r = storyOffer(run, ch, e, valueOf(e), amount);
      saved();
      const club = esc(clubName(e.squad.teamId));
      if (r.kind === 'accept') {
        redraw({ open: null, msg: `סגרנו! ${esc(e.player.name)} הצטרף ב-${money(r.price)} ₪` });
      } else if (r.kind === 'counter') {
        redraw({ amt: amount, talkMsg: `${club}: "בשביל ${money(r.counter)} ₪ הוא שלך."` });
      } else if (r.kind === 'reject') {
        redraw({ amt: amount, talkMsg: r.left > 0 ? `${club} דחתה את ההצעה של ${money(amount)} ₪.` : `${club} דחתה, והפסיקה לענות.` });
      } else {
        redraw({ amt: amount, talkMsg: blockedMsg(r.why) });
      }
    });
    $('[data-take]').forEach(b => b.onclick = () => {
      const e = byKey(b.dataset.take);
      const r = storyTakeCounter(run, ch, e, valueOf(e));
      saved();
      redraw(r.kind === 'accept'
        ? { open: null, msg: `סגרנו! ${esc(e.player.name)} הצטרף ב-${money(r.price)} ₪` }
        : { talkMsg: blockedMsg(r.why) });
    });
    byId('st-form').onchange = ev => {
      run.formationId = ev.target.value;
      if (!formationTactical(run.formationId)) run.tactic = 'bal';
      saved();
      redraw({ msg: '' });
    };
    byId('st-tac').onchange = ev => {
      run.tactic = ev.target.value;
      saved();
      redraw({ msg: '' });
    };
    const qEl = byId('st-q');
    qEl.onchange = () => redraw({ q: qEl.value, msg: '', open: null });
    byId('st-pos').onchange = ev => redraw({ pos: ev.target.value, msg: '', open: null });
    byId('st-afford').onchange = ev => redraw({ afford: ev.target.checked, msg: '', open: null });
    byId('st-done').onclick = ctx.onDone;
  }

  /* ── the lineup ─────────────────────────────────────────────────────────── */
  // Pick the eleven yourself, slot by slot, or leave it to "הרכב אוטומטי". The
  // choice is kept by slot (run.xi); injured men cannot be picked and a pick who
  // gets injured is covered from the bench automatically.
  function lineupHTML(run, lineup, hurt) {
    const owned = storyOwned(run).filter(e => !hurt.has(e.player.name))
      .sort((a, b) => b.player.ovr - a.player.ovr);
    const keyOf = e => e.squad.id + '|' + e.player.name;
    const rows = lineup.slots.map((s, i) => {
      const cur = lineup.picks[i];
      const pos = slotFitPos(s);
      const fits = owned.filter(e => playerFitsSlot(e.player, pos));
      const others = owned.filter(e => !playerFitsSlot(e.player, pos));
      const opt = (e, off) => `<option value="${esc(keyOf(e))}"${cur && keyOf(cur) === keyOf(e) ? ' selected' : ''}>${
        e.player.ovr} · ${esc(e.player.name)}${off ? ' (לא בעמדה)' : ''}</option>`;
      return `<label class="lu-row"><span>${esc(s.label || posHe(pos))}</span>
        <select data-slot="${esc(s.id)}">${fits.map(e => opt(e, false)).join('')}${others.map(e => opt(e, true)).join('')}</select></label>`;
    }).join('');
    const b = lineup.bench;
    const auto = !run.xi || !Object.keys(run.xi).length;
    return `<details class="lu"${auto ? '' : ' open'}><summary>ההרכב ${auto ? '(אוטומטי)' : '(שלך)'} · לחצו לבחירה</summary>
      <div class="lu-grid">${rows}</div>
      <p class="st-note">המחליפים הטובים ביותר בספסל (משחקים כ-10% מהדקות): התקפה ${Math.round(b.atk)} ·
        קישור ${Math.round(b.mid)} · הגנה ${Math.round(b.def)}. ספסל חלש מוריד את הקבוצה בכל משחק.</p>
      ${auto ? '' : '<button class="st-b" data-lu-auto>הרכב אוטומטי</button>'}</details>`;
  }
  function wireLineup(host, run, lineup, onChange) {
    const keyOf = e => e.squad.id + '|' + e.player.name;
    host.querySelectorAll('select[data-slot]').forEach(sel => sel.onchange = () => {
      const xi = {};
      lineup.slots.forEach((s, i) => { if (lineup.picks[i]) xi[s.id] = keyOf(lineup.picks[i]); });
      // the man picked here leaves wherever else he stood
      for (const k of Object.keys(xi)) if (xi[k] === sel.value) delete xi[k];
      xi[sel.dataset.slot] = sel.value;
      run.xi = xi;
      onChange();
    });
    const auto = host.querySelector('[data-lu-auto]');
    if (auto) auto.onclick = () => { run.xi = {}; onChange(); };
  }

  function storyShowMarket() {
    ensureStyle();
    const run = storyRun();
    const ch = run && storyChapter(run.chapterId);
    if (!ch) { storyShowHub(); return; }
    showScreen('story');
    renderMarket({ run, ch, window: 'summer', when: 'h1', statOf: () => null, host: root(),
                   persist: storySave, onDone: storyEnterSeason });
  }

  function storyShowJanuary(pair, tally, draft, onDone) {
    ensureStyle();
    const ch = storyChapter(draft.chapterId);
    const wrap = document.createElement('div');
    wrap.className = 'st-wrap';
    const pts = tally.wins * 3 + tally.draws;
    wrap.innerHTML = `<div class="st-box" role="dialog" aria-modal="true">
      <p style="margin:0 0 10px;color:var(--dim);font-size:13px">חצי הדרך:
        <b dir="ltr" style="color:var(--text)">${tally.wins}-${tally.draws}-${tally.losses}</b>,
        ${pts} נק׳ אחרי ${pair.played} מחזורים</p>
      <div id="st-jan"></div></div>`;
    document.body.appendChild(wrap);
    const statOf = name => pair.firstStats.find(s => s.name === name) || null;
    renderMarket({ run: draft, ch, window: 'jan', when: 'h2', statOf, host: wrap.querySelector('#st-jan'),
                   onDone: () => { wrap.remove(); onDone(); } });
  }

  /* ── Europe: the campaign board ─────────────────────────────────────────── */
  // One screen for the whole campaign: the road (every round, with where you
  // are), then the round in front of you — the tie or the group table, what you
  // need, and the one decision: how you play the next match.
  const venue = (round, home) => home === true ? 'בבית' : home === false
    ? (round.oneLeg ? 'אצלם' : 'בחוץ') : 'במגרש ניטרלי';
  function euLegLine(us, leg, oppName) {
    const sc = (leg.scorers || []).map(s => `${esc(s.n)} ${s.min}'`).join(' · ');
    return `<div class="eu-leg ${leg.gf > leg.ga ? 'w' : leg.gf < leg.ga ? 'l' : 'd'}">
      <b>${esc(us)} <bdi dir="ltr">${leg.gf}-${leg.ga}</bdi> ${esc(oppName)}</b>
      <span>${venue({}, leg.home)} · ${esc(TACTICS[leg.tactic] ? TACTICS[leg.tactic].label : '')}</span>
      ${sc ? `<em>⚽ ${sc}</em>` : ''}</div>`;
  }
  function euTableHTML(ch, table, round) {
    const us = clubName(ch.teamId);
    return `<table class="eu-tbl"><tr><th></th><th>קבוצה</th><th>מש׳</th><th>הפרש</th><th>נק׳</th></tr>
      ${table.map((r, i) => `<tr class="${r.us ? 'us' : ''}"><td>${i + 1}</td><td>${r.us ? crestImg(ch.teamId) : oppMark(((round && round.clubs) || []).find(c => c.name === r.name) || {})}${esc(r.us ? us : r.name)}</td>
        <td>${r.p}</td><td><bdi dir="ltr">${r.gd > 0 ? '+' : ''}${r.gd}</bdi></td><td><b>${r.pts}</b></td></tr>`).join('')}</table>`;
  }

  function storyShowEurope(view) {
    ensureStyle();
    showScreen('story');
    const back = document.getElementById('story-back');
    if (back) back.onclick = storyShowHub;
    const run = storyRun();
    const ch = run && storyChapter(run.chapterId);
    if (!ch || !run.eu) { storyShowHub(); return; }
    view = view || {};
    const us = clubName(ch.teamId);
    const rounds = ch.europe.rounds;
    const over = storyEuOver(ch, run);
    const doneById = id => run.eu.done.find(d => d.id === id);

    const road = rounds.map((r, i) => {
      const d = doneById(r.id);
      const cls = d ? (d.won ? 'ok' : 'out') : (i === run.eu.at && !over ? 'now' : '');
      const mark = d ? (d.won ? '✓' : '✗') : (i === run.eu.at && !over ? '●' : '○');
      return `<span class="eu-step ${cls}">${mark} ${esc(r.label)}</span>`;
    }).join('');

    // the last match, and the round it closed
    // Only once the match closed a round: mid-tie the round card already shows it.
    let lastHTML = '';
    if (view.last && view.last.closed) {
      const L = view.last, r = L.round;
      const oppName = r.kind === 'tie' ? r.club.name : (L.leg.opp || '');
      // A finished tie shows BOTH legs, then the aggregate. Showing only the leg just
      // played read as "0-0, so how is it 1-0?" — the first leg was off screen.
      const legs = L.closed.kind === 'tie' ? L.closed.legs : [L.leg];
      const head = L.closed.kind === 'tie'
        ? `<h3>${oppMark(r.club)} ${esc(r.club.name)} · ${esc(r.label)}</h3>` : '';
      lastHTML = `<div class="eu-card last">${head}${legs.map(l => euLegLine(us, l, oppName)).join('')}`;
      if (L.closed && L.closed.kind === 'tie') {
        const c = L.closed;
        const how = c.how === 'away' ? ' (שערי חוץ)' : c.how === 'et' ? ' (אחרי הארכה)' : c.how === 'pens'
          ? ` (בפנדלים <bdi dir="ltr">${c.pens.gf}-${c.pens.ga}</bdi>)` : '';
        lastHTML += `<div class="eu-verdict ${c.won ? 'ok' : 'out'}">${c.won ? 'עליתם!' : 'הודחתם.'}
          סיכום <bdi dir="ltr">${c.agg.gf}-${c.agg.ga}</bdi>${how}</div>
          <div class="st-note">במציאות: ${esc(r.real)}</div>`;
      }
      if (L.closed && L.closed.kind === 'group') {
        lastHTML += `<div class="eu-verdict ${L.closed.won ? 'ok' : 'out'}">סיימתם במקום ${L.closed.pos} בבית</div>
          ${euTableHTML(ch, L.closed.table, r)}<div class="st-note">במציאות: ${esc(r.real)}</div>`;
      }
      lastHTML += '</div>';
    }

    let main = '';
    if (over) {
      main = `<div id="st-eu-end"></div>`;
    } else if (storyEuWindowDue(ch, run)) {
      main = `<div class="eu-card"><h3>חלון ההעברות</h3>
        <p class="st-note">לפני ${esc(storyEuRound(ch, run).label)} נפתח חלון: עד ${storyRules(ch).buys.jan} רכישות.
          המחירים של השחקנים שלך נקבעים לפי מה שעשו באירופה עד עכשיו.</p>
        <button class="st-b go st-go" id="eu-window">לחלון ההעברות</button>
        <button class="st-b st-go" id="eu-skip">לוותר על החלון</button></div>`;
    } else {
      const r = storyEuRound(ch, run);
      const cur = run.eu.cur || { legs: [], played: [] };
      const tac = view.tactic || 'bal';
      let body = '';
      if (r.kind === 'tie') {
        const i = cur.legs.length;
        const home = r.oneLeg ? r.home : (i === 0) === !!r.firstHome;
        body = `<h3>${esc(r.label)}: ${oppMark(r.club)} ${esc(r.club.name)} <span class="st-tag">${r.club.ovr}</span></h3>
          ${cur.legs.map(l => euLegLine(us, l, r.club.name)).join('')}
          <p class="eu-next">${r.oneLeg ? 'משחק יחיד' : `משחק ${i + 1} מתוך 2`} · ${venue(r, home)}</p>
          ${storyEuNeed(ch, r, cur.legs) ? `<p class="eu-need">${esc(storyEuNeed(ch, r, cur.legs))}</p>` : ''}
          ${r.ko && r.club.ovr > storyXiOvr(run, storyEuWhen(run, r))
            ? '<p class="st-note">לילה אירופי: מול יריבה חזקה ממכם, הקבוצה שלכם מתעלה.</p>' : ''}`;
      } else {
        const i = cur.legs.length;
        const fx = r.fixtures[i];
        const opp = r.clubs[fx[0]];
        body = `<h3>${esc(r.label)} · מחזור ${i + 1} מתוך 6</h3>
          ${euTableHTML(ch, storyEuLiveTable(ch, run), r)}
          ${cur.legs.map(l => euLegLine(us, l, l.opp)).join('')}
          <p class="eu-next">הבא: ${oppMark(opp)} ${esc(opp.name)} <span class="st-tag">${opp.ovr}</span> · ${venue(r, fx[1])}</p>
          <p class="st-note">שתיים הראשונות עולות. אין כאן לילה אירופי: שש פעמים מול הטובות באירופה.</p>`;
      }
      // who misses the next match, and the eleven that will play it
      const when = storyEuWhen(run, r);
      const hurtEu = new Set(storyInjured(run, when).map(e => e.player.name));
      const lu = storyLineup(run, when);
      view.lu = lu;
      main = `<div class="eu-card">${body}
        ${hurtEu.size ? `<p class="st-hurt">🩹 לא ישחקו במשחק הזה: ${[...hurtEu].map(esc).join(', ')}</p>` : ''}
        ${lineupHTML(run, lu, hurtEu)}
        <div class="eu-tac">${TACTIC_KEYS.map(k => `<button class="st-b${k === tac ? ' go' : ''}" data-tac="${k}">
          ${esc(TACTICS[k].label)}<small>${tacticTrade(k) || 'בלי שינוי'}</small></button>`).join('')}</div>
        <button class="st-b go st-go" id="eu-play">לשחק את המשחק</button></div>`;
    }

    root().innerHTML = `
      <p class="st-kick">${crestImg(ch.teamId)}${esc(ch.comp)} · ${esc(us)} ${esc(ch.season)}</p>
      <div class="eu-road">${road}</div>
      ${lastHTML}${main}`;

    const byId = id => root().querySelector('#' + id);
    if (over) storyRenderEnd(ch, run.result, byId('st-eu-end'));
    if (view.lu) wireLineup(root(), run, view.lu, () => { storySave(); storyShowEurope({ tactic: view.tactic }); });
    root().querySelectorAll('[data-tac]').forEach(b => b.onclick = () =>
      storyShowEurope({ ...view, tactic: b.dataset.tac }));
    const play = byId('eu-play');
    if (play) play.onclick = () => {
      const out = storyEuAct(view.tactic || 'bal');
      storyShowEurope({ last: out, tactic: view.tactic || 'bal' });
    };
    const win = byId('eu-window');
    if (win) win.onclick = () => {
      run.phase = 'jan';
      storySave();
      const statOf = name => run.eu.stats[name] || null;
      renderMarket({ run, ch, window: 'jan', when: storyEuWhen(run, storyEuRound(ch, run)), statOf, host: root(), persist: storySave,
        doneLabel: 'חזרה למסע', onDone: () => { storyEuWindowClose(); storyShowEurope(); } });
    };
    const skip = byId('eu-skip');
    if (skip) skip.onclick = () => { storyEuWindowClose(); storyShowEurope(); };
  }

  /* ── the verdict ─────────────────────────────────────────────────────────── */
  function storyRenderEnd(ch, r, target) {
    ensureStyle();
    const box = target || document.getElementById('story-end-box');
    if (!box || !r) return;
    const real = storyReal(ch);
    const best = storyBest()[ch.id];
    box.innerHTML = `<div class="st-end">
      <p style="margin:0 0 4px;color:var(--dim);font-size:13px">${crestImg(ch.teamId)}${esc(clubName(ch.teamId))} ${esc(ch.season)}: ${esc(titleOf(ch))}</p>
      ${starsHTML(r.stars)}
      <ul class="st-goals" style="text-align:right">${ch.stars.map((s, i) => {
        // Graded: the first star missed is ❌, the ones after it are locked, not failed.
        const miss = r.stars.indexOf(false);
        const mark = r.stars[i] ? '✅' : (i === miss ? '❌' : '🔒');
        return `<li>${mark} ${esc(starLabel(ch, i))}</li>`;
      }).join('')}</ul>
      <div class="st-vs">${r.eu ? `
        <div><i>אתם</i><b>${r.eu.champion ? 'זכייה בגביע!' : 'עד ' + esc(storyEuRoundLabel(ch, r.eu.reached))}${r.eu.group
          ? ` · ${r.eu.group.pts} נק׳ בבית, <bdi dir="ltr">${r.eu.group.gf}-${r.eu.group.ga}</bdi>` : ''}</b></div>
        <div><i>המציאות</i><b>${esc(realTextOf(ch))}</b></div>` : `
        <div><i>אתם</i><b>מקום ${r.rank} · ${num(r.points)} נק׳</b></div>
        <div><i>המציאות</i><b>מקום ${real ? real.pos : '?'} · ${real ? real.pts : '?'} נק׳</b></div>`}
      </div>
      <p style="margin:0 0 4px">תקציב בסוף: <b>${money(r.budget)}</b> (פתיחה: ${money(ch.budget)})</p>
      <p style="margin:0 0 12px">ניקוד: <b>${num(r.score)}</b>${best ? ` · השיא שלך: <b>${num(best.score)}</b>` : ''}</p>
      <div style="display:flex;gap:8px">
        <button class="st-b go" id="st-again" style="flex:1">לשחק שוב</button>
        <button class="st-b" id="st-chapters" style="flex:1">לפרקים</button>
      </div></div>`;
    document.getElementById('st-again').onclick = () => storyStart(ch.id);
    document.getElementById('st-chapters').onclick = storyExit;
  }

  // Any season that is NOT a chapter must not show the last chapter's verdict.
  function storyClearEnd() {
    const box = document.getElementById('story-end-box');
    if (box) box.innerHTML = '';
  }

  document.addEventListener('DOMContentLoaded', () => {
    const card = document.getElementById('setup-story-card');
    if (card) card.addEventListener('click', storyShowHub);
  });

  Object.assign(global, { storyShowHub, storyShowIntro, storyShowMarket, storyShowJanuary, storyShowEurope,
                          storyRenderEnd, storyClearEnd });
})(typeof window !== 'undefined' ? window : globalThis);
