// Bakes the approved star tags into js/tag-data.js.
//
// star_tags.csv is the curated source (flip `keep` to n to drop a row); this
// turns whatever survived into the lookup the game reads. Names are normalised
// the same way every other name comparison on the site is.
//
//   node scripts/build_tag_js.js
const fs = require('fs');
const path = require('path');

const CSV = path.join(__dirname, '..', 'star_tags.csv');
const OUT = path.join(__dirname, '..', 'js', 'tag-data.js');
const R = f => fs.readFileSync(path.join(__dirname, '..', f), 'utf8');
const LT = new Function(
  R('js/league_tables.js') +
  ';\nreturn { LEAGUE_TABLES, LEAGUE_SCORERS, LEAGUE_ASSISTS };'
)();

const norm = s => String(s ?? '')
  .replace(/[‎‏‪-‮⁦-⁩]/g, '')
  .replace(/[׳’`´']/g, "'")
  .replace(/\s+/g, ' ')
  .trim();

function split(line) {
  const out = []; let cur = '', q = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (q) {
      if (c === '"' && line[i + 1] === '"') { cur += '"'; i++; }
      else if (c === '"') q = false;
      else cur += c;
    } else if (c === '"') q = true;
    else if (c === ',') { out.push(cur); cur = ''; }
    else cur += c;
  }
  out.push(cur);
  return out;
}

const lines = fs.readFileSync(CSV, 'utf8').replace(/^﻿/, '').split(/\r?\n/).filter(Boolean);
const head = split(lines[0]);
const rows = lines.slice(1).map(l => {
  const c = split(l), r = {};
  head.forEach((h, i) => { r[h] = c[i]; });
  return r;
}).filter(r => (r.keep || 'y').toLowerCase() !== 'n');

// name → [[tagKey, count, evidence], ...]
const byPlayer = {};
for (const r of rows) {
  const k = norm(r.player);
  (byPlayer[k] = byPlayer[k] || []).push([r.tag, +r.count || 1, r.evidence || '']);
}

/* ── the real numbers, for the card ───────────────────────────────────────── */
// Only what actually happened: the goals and assists a player was credited with
// in the real season lists, and who won the league / conceded fewest that year.
// Nothing is estimated, and a player who never made a list simply has none.
const real = {};
const addReal = (table, field) => Object.keys(table || {}).forEach(season =>
  (table[season] || []).forEach(r => {
    const k = norm(r.name);
    (real[k] = real[k] || { g: [], a: [] })[field].push([season, r.n, r.r]);
  }));
addReal(LT.LEAGUE_SCORERS, 'g');
addReal(LT.LEAGUE_ASSISTS, 'a');

// season → [champion club, best-defence club, goals that defence conceded]
const seasons = {};
Object.keys(LT.LEAGUE_TABLES).forEach(season => {
  const rows = LT.LEAGUE_TABLES[season] || [];
  const champ = rows.find(r => r.pos === 1);
  const withGa = rows.filter(r => typeof r.ga === 'number');
  const best = withGa.length ? withGa.reduce((x, y) => (y.ga < x.ga ? y : x)) : null;
  seasons[season] = [champ ? champ.teamId : '', best ? best.teamId : '', best ? best.ga : 0];
});

const names = Object.keys(byPlayer).sort();
const body = names.map(n =>
  `  ${JSON.stringify(n)}: ${JSON.stringify(byPlayer[n])},`).join('\n');

fs.writeFileSync(OUT, `// GENERATED by scripts/build_tag_js.js — do not edit by hand.
//
// What each of the league's notable players actually did, as
//   "player name" (normalised): [[tag key, how many times, the evidence], ...]
// Every row is a fact from the real tables — titles, golden boots, the
// Footballer of the Season vote — never an opinion. See js/tags.js for what the
// game does with them.
const TAG_DATA = {
${body}
};

// The real season numbers behind those tags:
//   "player": { g: [[season, goals, rank], ...], a: [[season, assists, rank], ...] }
// Straight from the league's own top-scorer and top-assist lists, so a player
// only appears for the seasons in which he made one.
const PLAYER_REAL = ${JSON.stringify(real, null, 0)};

// season → [champion, tightest defence, goals that defence conceded]
const SEASON_FACTS = ${JSON.stringify(seasons, null, 0)};
`, 'utf8');

console.log(`wrote ${names.length} players (${rows.length} tags), ` +
  `${Object.keys(real).length} with real season numbers, to js/tag-data.js`);
