// Builds js/story-facts.js — the few rows of js/league_tables.js that מצב סיפור
// reads in the browser.
//
//   node scripts/build_story_facts.js
//
// js/league_tables.js is 92KB and is not loaded by the site at all: it is an input
// to the generators. The chapters need a sliver of it — each chapter season's
// table (the "reality" line), the season before it (who counts as a rival), and
// that season's top scorers and assisters (the reputation premium). Loading the
// whole file for that would cost every visitor 92KB, and loading it lazily would
// escape scripts/stamp_assets.js, which only stamps what index.html names — an
// unstamped URL is cached for a year. So the sliver is generated, and the tables
// stay the one source. Re-run after adding a chapter or rebuilding the tables.
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const read = f => fs.readFileSync(path.join(ROOT, f), 'utf8');

const T = new Function(read('js/league_tables.js') +
  ';return { LEAGUE_TABLES, LEAGUE_SCORERS, LEAGUE_ASSISTS };')();
const C = new Function(read('js/story-data.js') + ';return STORY_CHAPTERS;')();

const prev = s => { const y = parseInt(s, 10); return `${y - 1}/${String(y).slice(-2)}`; };
const tables = {}, reps = {};
for (const ch of C) {
  for (const s of [ch.season, prev(ch.season)]) {
    if (T.LEAGUE_TABLES[s]) tables[s] = T.LEAGUE_TABLES[s].map(r => ({ teamId: r.teamId, pos: r.pos, pts: r.pts }));
  }
  const p = prev(ch.season);
  reps[p] = [...new Set([...(T.LEAGUE_SCORERS[p] || []), ...(T.LEAGUE_ASSISTS[p] || [])].map(r => r.name))];
}

const out = `/* Generated by scripts/build_story_facts.js from js/league_tables.js — do not edit by hand.
 * The rows מצב סיפור reads in the browser: each chapter season's final table, the
 * season before it, and that season's top scorers and assisters. */
const STORY_FACTS = ${JSON.stringify({ tables, reps })};
`;
fs.writeFileSync(path.join(ROOT, 'js/story-facts.js'), out);
console.log(`js/story-facts.js: ${Object.keys(tables).length} tables (${Object.keys(tables).join(', ')}), ` +
            `${Object.values(reps).reduce((a, r) => a + r.length, 0)} reputation names, ${out.length} bytes`);
