// Bakes the approved chemistry pairs into js/chem-data.js.
//
// The CSV is the curated source (flip `keep` to n to drop a pair); this turns
// whatever survived into the lookup the game reads. Keys are the two names,
// normalised the same way every other name comparison on the site is and sorted
// so the pair reads the same from either side.
//
//   node scripts/build_chem_js.js
const fs = require('fs');
const path = require('path');

const CSV = path.join(__dirname, '..', 'chemistry_duos.csv');
const OUT = path.join(__dirname, '..', 'js', 'chem-data.js');

// same normalisation as crNormName / mgNorm
const norm = s => String(s ?? '')
  .replace(/[‎‏‪-‮⁦-⁩]/g, '')
  .replace(/[׳’`´']/g, "'")
  .replace(/\s+/g, ' ')
  .trim();

// a tiny CSV reader — the file is ours and quoting is simple
function parse(text) {
  const rows = [];
  const lines = text.replace(/^﻿/, '').split(/\r?\n/).filter(Boolean);
  const head = split(lines[0]);
  for (let i = 1; i < lines.length; i++) {
    const cells = split(lines[i]);
    const rec = {};
    head.forEach((h, j) => { rec[h] = cells[j]; });
    rows.push(rec);
  }
  return rows;
}
function split(line) {
  const out = []; let cur = '', q = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (q) {
      if (c === '"' && line[i + 1] === '"') { cur += '"'; i++; }
      else if (c === '"') q = false;
      else cur += c;
    } else if (c === '"') q = true;
    else if (c === ',') { out.push(cur); cur = ''; }
    else cur += c;
  }
  out.push(cur);
  return out;
}

const rows = parse(fs.readFileSync(CSV, 'utf8'))
  .filter(r => (r.keep || 'y').toLowerCase() !== 'n');

const pairs = {};
const meta = {};
for (const r of rows) {
  const a = norm(r.player_a), b = norm(r.player_b);
  if (!a || !b) continue;
  const key = [a, b].sort().join('|');
  const tier = Math.max(1, Math.min(3, +r.tier || 1));
  if (!pairs[key] || pairs[key] < tier) {
    pairs[key] = tier;
    meta[key] = { s: +r.seasons_together || 0, t: +r.titles_together || 0 };
  }
}

const keys = Object.keys(pairs).sort();
const body = keys.map(k => `  ${JSON.stringify(k)}: [${pairs[k]},${meta[k].s},${meta[k].t}],`).join('\n');

fs.writeFileSync(OUT, `// GENERATED by scripts/build_chem_js.js — do not edit by hand.
//
// Every pair that survived curation in chemistry_duos.csv, as
//   "name a|name b" (normalised, sorted): [tier, seasons together, titles together]
// The tier is the bonus: +1, +2 or +3. See js/chemistry.js for what the game
// does with it.
const CHEM_PAIRS = {
${body}
};
`, 'utf8');

console.log(`wrote ${keys.length} pairs to js/chem-data.js`);
