// coaches.csv → js/coach-data.js
//
// The CSV is the editable source and it is gitignored (*.csv, the repo's own
// convention), so the game cannot read it. This turns it into a committed JS
// file the same way build_tag_js.js does for the star tags.
//
// Nothing here invents anything. Every field is copied from the CSV; a manager
// with no playing_style comes out with no style, and the card is expected to
// cope with that rather than have one made up for him.
//
// Run: node scripts/build_coaches.js  [--print]
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'coaches.csv');
const OUT = path.join(__dirname, '..', 'js', 'coach-data.js');

// A small CSV reader rather than a dependency: quoted fields with embedded
// commas and doubled quotes are the only two cases the file actually uses.
function parseCSV(text) {
  const rows = [];
  let row = [], field = '', q = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (q) {
      if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else q = false; }
      else field += c;
    } else if (c === '"') q = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); field = ''; rows.push(row); row = []; }
    else if (c !== '\r') field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows.filter(r => r.some(x => x.trim() !== ''));
}

const raw = fs.readFileSync(SRC, 'utf8').replace(/^﻿/, '');
const rows = parseCSV(raw);
const head = rows[0].map(h => h.trim());
const col = name => head.indexOf(name);

const need = ['name', 'league_titles_since_1999_00', 'title_seasons',
              'state_cups_since_1999_00', 'cup_seasons', 'main_clubs',
              'playing_style', 'note', 'wikipedia'];
for (const n of need) if (col(n) < 0) throw new Error(`coaches.csv is missing the "${n}" column`);

const list = rows.slice(1).map(r => {
  const g = n => (r[col(n)] ?? '').trim();
  const semi = s => s ? s.split(';').map(x => x.trim()).filter(Boolean) : [];
  const o = {
    name:   g('name'),
    titles: +g('league_titles_since_1999_00') || 0,
    cups:   +g('state_cups_since_1999_00') || 0,
    titleSeasons: semi(g('title_seasons')),
    cupSeasons:   semi(g('cup_seasons')),
    clubs:  semi(g('main_clubs')),
    note:   g('note'),
    wiki:   g('wikipedia'),
  };
  const style = g('playing_style');
  if (style) o.style = style;          // absent, not empty, when we do not know
  return o;
}).filter(c => c.name);

// Fail loudly rather than shipping a half file: a name collision would make two
// managers the same man everywhere downstream.
const seen = new Set();
for (const c of list) {
  if (seen.has(c.name)) throw new Error(`duplicate coach: ${c.name}`);
  seen.add(c.name);
}

const withStyle = list.filter(c => c.style).length;
const body = list.map(c => '  ' + JSON.stringify(c)).join(',\n');
fs.writeFileSync(OUT,
`/* Generated by scripts/build_coaches.js from coaches.csv — do not edit by hand.
 *
 * ${list.length} managers of Israeli top-flight clubs since 1999/00, with what
 * they actually won. \`style\` is present only for the ${withStyle} whose playing
 * style is documented; the rest genuinely have none recorded, and anything that
 * renders a manager has to handle its absence rather than invent one.
 */
const COACHES = [
${body}
];
if (typeof module !== 'undefined') module.exports = { COACHES };
`, 'utf8');

console.log(`wrote ${path.relative(path.join(__dirname, '..'), OUT)} — ${list.length} managers, ` +
            `${list.filter(c => c.titles > 0).length} with a league title, ${withStyle} with a playing style`);
if (process.argv.includes('--print')) {
  for (const c of list) {
    console.log(`${c.titles}🏆 ${c.cups}🏅  ${c.name}  [${c.clubs.join(', ')}]${c.style ? '  · ' + c.style : ''}`);
  }
}
