// coaches.csv → js/coach-data.js
//
// The CSV is the editable source and it is gitignored (*.csv, the repo's own
// convention), so the game cannot read it. This turns it into a committed JS
// file the same way build_tag_js.js does for the star tags.
//
// Nothing here invents anything. Every field is copied from the CSV; a manager
// with no playing_style comes out with no style, and the card is expected to
// cope with that rather than have one made up for him.
//
// Run: node scripts/build_coaches.js  [--print]
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'coaches.csv');
const OUT = path.join(__dirname, '..', 'js', 'coach-data.js');

// A small CSV reader rather than a dependency: quoted fields with embedded
// commas and doubled quotes are the only two cases the file actually uses.
function parseCSV(text) {
  const rows = [];
  let row = [], field = '', q = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (q) {
      if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else q = false; }
      else field += c;
    } else if (c === '"') q = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); field = ''; rows.push(row); row = []; }
    else if (c !== '\r') field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows.filter(r => r.some(x => x.trim() !== ''));
}

const raw = fs.readFileSync(SRC, 'utf8').replace(/^﻿/, '');
const rows = parseCSV(raw);
const head = rows[0].map(h => h.trim());
const col = name => head.indexOf(name);

const need = ['name', 'league_titles_since_1999_00', 'title_seasons',
              'state_cups_since_1999_00', 'cup_seasons', 'main_clubs',
              'playing_style', 'note', 'wikipedia', 'archetype', 'il_seasons'];
for (const n of need) if (col(n) < 0) throw new Error(`coaches.csv is missing the "${n}" column`);

// The archetype is what the SIMULATION reads. The style sentence next to it is
// free Hebrew prose written by hand, and no amount of matching on it at runtime
// would be honest — so the mapping is a column a human owns, and an unreadable
// value stops the build rather than quietly becoming a default.
const ARCHETYPES = ['grit', 'press', 'attack', 'control', 'order', 'spirit'];

// Tier is DERIVED, never written: it comes from the same title and cup counts
// already in the file, so it cannot drift away from them. It sets how hard a
// manager stamps his style on a season, not how good the season is.
function tierOf(titles, cups) {
  if (titles >= 3) return 'legend';
  if (titles >= 1) return 'winner';
  if (cups   >= 1) return 'cup';
  return 'journeyman';
}

const list = rows.slice(1).map(r => {
  const g = n => (r[col(n)] ?? '').trim();
  const semi = s => s ? s.split(';').map(x => x.trim()).filter(Boolean) : [];
  const titles = +g('league_titles_since_1999_00') || 0;
  const cups   = +g('state_cups_since_1999_00') || 0;
  const o = {
    name:   g('name'),
    titles, cups,
    titleSeasons: semi(g('title_seasons')),
    cupSeasons:   semi(g('cup_seasons')),
    clubs:  semi(g('main_clubs')),
    note:   g('note'),
    wiki:   g('wikipedia'),
    arch:   g('archetype'),
    tier:   tierOf(titles, cups),
  };
  // The seasons he was actually managing an ISRAELI CLUB, one by one — not a
  // span. A span would have marked Avram Grant as working every year from 1986
  // to 2025, Ghana included. Built from |שנים כמאמן= paired against
  // |קבוצות כמאמן= on his Hebrew Wikipedia page, with national teams, youth
  // sides and assistant roles dropped. Empty means unknown, and unknown means
  // eligible in every season rather than in a guessed one — the same rule
  // `style` follows.
  const yrs = g('il_seasons').split(';').map(x => +x).filter(Boolean);
  if (yrs.length) o.yrs = yrs;
  const style = g('playing_style');
  if (style) o.style = style;          // absent, not empty, when we do not know
  return o;
}).filter(c => c.name);

// Fail loudly rather than shipping a half file: a name collision would make two
// managers the same man everywhere downstream.
const seen = new Set();
for (const c of list) {
  if (seen.has(c.name)) throw new Error(`duplicate coach: ${c.name}`);
  seen.add(c.name);
}

// Same reasoning as the duplicate check: a manager with no archetype, or one
// with a typo in it, would silently become a manager who does nothing. The game
// has no sane default here, so there is nothing to fall back TO.
for (const c of list) {
  if (!ARCHETYPES.includes(c.arch)) {
    throw new Error(`coach "${c.name}" has archetype "${c.arch}" — expected one of ${ARCHETYPES.join(', ')}`);
  }
}

const withStyle = list.filter(c => c.style).length;
const tally = k => list.filter(c => c[k[0]] === k[1]).length;
const body = list.map(c => '  ' + JSON.stringify(c)).join(',\n');
fs.writeFileSync(OUT,
`/* Generated by scripts/build_coaches.js from coaches.csv — do not edit by hand.
 *
 * ${list.length} managers of Israeli top-flight clubs since 1999/00, with what
 * they actually won. \`style\` is present only for the ${withStyle} whose playing
 * style is documented; the rest genuinely have none recorded, and anything that
 * renders a manager has to handle its absence rather than invent one.
 *
 * \`arch\` is the archetype the simulation reads — the style sentence is prose and
 * is only ever shown, never parsed. \`tier\` is derived from the titles and cups
 * in the same row and decides how hard the man stamps his style on a season.
 */
const COACHES = [
${body}
];
if (typeof module !== 'undefined') module.exports = { COACHES };
`, 'utf8');

console.log(`wrote ${path.relative(path.join(__dirname, '..'), OUT)} — ${list.length} managers, ` +
            `${list.filter(c => c.titles > 0).length} with a league title, ${withStyle} with a playing style`);
console.log('tiers      ' + ['legend', 'winner', 'cup', 'journeyman'].map(t => `${t} ${tally(['tier', t])}`).join(' · '));
console.log('archetypes ' + ARCHETYPES.map(a => `${a} ${tally(['arch', a])}`).join(' · '));
console.log(`seasons    ${list.filter(c => c.yrs).length}/${list.length} with Israeli-club seasons · ` +
            `median ${(() => { const n = list.filter(c => c.yrs).map(c => c.yrs.length).sort((a, b) => a - b); return n[n.length >> 1]; })()} seasons each`);
if (process.argv.includes('--print')) {
  for (const c of list) {
    console.log(`${c.titles}🏆 ${c.cups}🏅  ${c.name}  [${c.clubs.join(', ')}]${c.style ? '  · ' + c.style : ''}`);
  }
}
